package itin_pc.view;

import itin_pc.controller.EmpleadoControlador;
import itin_pc.controller.UsuarioControlador;
import itin_pc.model.Empleado;
import itin_pc.model.Usuario;
import itin_pc.util.Excepciones;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ActualizarEmpleado extends javax.swing.JFrame {

    private final EmpleadoControlador e;
    private final UsuarioControlador u;

    private final int empleadoId;

    Empleado empleadoActualizar;
    Usuario usuarioActualizar;

    private int initX, initY;

    public ActualizarEmpleado(int empleadoId) {

        this.e = new EmpleadoControlador();
        this.u = new UsuarioControlador();

        this.empleadoId = empleadoId;

        initComponents();
        this.setLocationRelativeTo(null);

        verDatosEmpleado();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActions = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelRound14 = new jilmar.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlRegistroEmpleado = new jilmar.PanelRound();
        lblResumen1 = new javax.swing.JLabel();
        panelRound4 = new jilmar.PanelRound();
        txtNombre = new javax.swing.JTextField();
        panelRound1 = new jilmar.PanelRound();
        cmbPuesto = new javax.swing.JComboBox<>();
        panelRound15 = new jilmar.PanelRound();
        txtApellido = new javax.swing.JTextField();
        panelRound16 = new jilmar.PanelRound();
        txtCargo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnLimpiarFormulario = new jilmar.LabelRound();
        bntRegistrarEmpleado = new jilmar.LabelRound();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelActions.setBackground(new java.awt.Color(215, 235, 255));
        panelActions.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelActionsMouseDragged(evt);
            }
        });
        panelActions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelActionsMousePressed(evt);
            }
        });
        panelActions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_icono.png"))); // NOI18N
        panelActions.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        lblTitle.setBackground(new java.awt.Color(0, 51, 153));
        lblTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 153));
        lblTitle.setText("ITIN-PC Mundo Tecnologico");
        panelActions.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 0, -1, 30));

        btnExit.setBackground(new java.awt.Color(215, 235, 255));
        btnExit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 51, 153));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        panelActions.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 50, 30));

        getContentPane().add(panelActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 30));

        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound14.setBackground(new Color(255, 255, 255,80));
        panelRound14.setRoundBottomLeft(30);
        panelRound14.setRoundBottomRight(30);
        panelRound14.setRoundTopLeft(30);
        panelRound14.setRoundTopRight(30);
        panelRound14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_icon_50x50.png"))); // NOI18N
        panelRound14.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestion de Empleados");
        panelRound14.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Administracion de Personal");
        panelRound14.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jPanel1.add(panelRound14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 370, 80));

        pnlRegistroEmpleado.setBackground(new Color(255, 255, 255, 230));
        pnlRegistroEmpleado.setRoundBottomLeft(30);
        pnlRegistroEmpleado.setRoundBottomRight(30);
        pnlRegistroEmpleado.setRoundTopLeft(30);
        pnlRegistroEmpleado.setRoundTopRight(30);
        pnlRegistroEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblResumen1.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 20)); // NOI18N
        lblResumen1.setForeground(new java.awt.Color(0, 51, 153));
        lblResumen1.setText("Editar Datos Empleado");
        pnlRegistroEmpleado.add(lblResumen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(15);
        panelRound4.setRoundBottomRight(15);
        panelRound4.setRoundTopLeft(15);
        panelRound4.setRoundTopRight(15);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 14)); // NOI18N
        txtNombre.setText("Jose");
        txtNombre.setBorder(null);
        panelRound4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, 40));

        pnlRegistroEmpleado.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 310, 40));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(15);
        panelRound1.setRoundBottomRight(15);
        panelRound1.setRoundTopLeft(15);
        panelRound1.setRoundTopRight(15);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbPuesto.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 14)); // NOI18N
        cmbPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rol...", "VENDEDOR", "TECNICO", "ADMIN" }));
        cmbPuesto.setBorder(null);
        panelRound1.add(cmbPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 280, 40));

        pnlRegistroEmpleado.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 310, 40));

        panelRound15.setBackground(new java.awt.Color(255, 255, 255));
        panelRound15.setRoundBottomLeft(15);
        panelRound15.setRoundBottomRight(15);
        panelRound15.setRoundTopLeft(15);
        panelRound15.setRoundTopRight(15);
        panelRound15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApellido.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 14)); // NOI18N
        txtApellido.setText("Lopez");
        txtApellido.setBorder(null);
        panelRound15.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, 40));

        pnlRegistroEmpleado.add(panelRound15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 310, 40));

        panelRound16.setBackground(new java.awt.Color(255, 255, 255));
        panelRound16.setRoundBottomLeft(15);
        panelRound16.setRoundBottomRight(15);
        panelRound16.setRoundTopLeft(15);
        panelRound16.setRoundTopRight(15);
        panelRound16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCargo.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 14)); // NOI18N
        txtCargo.setText("Vendedor De PC Gamers");
        txtCargo.setBorder(null);
        panelRound16.add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, 40));

        pnlRegistroEmpleado.add(panelRound16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 310, 40));

        jLabel8.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Puesto");
        pnlRegistroEmpleado.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 50, -1));

        jLabel21.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Nombre");
        pnlRegistroEmpleado.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, -1));

        jLabel23.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Apellido");
        pnlRegistroEmpleado.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 70, -1));

        jLabel24.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Cargo");
        pnlRegistroEmpleado.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 40, -1));

        btnLimpiarFormulario.setBackground(new java.awt.Color(153, 153, 153));
        btnLimpiarFormulario.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLimpiarFormulario.setText("Cancelar");
        btnLimpiarFormulario.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        btnLimpiarFormulario.setRoundBottomLeft(40);
        btnLimpiarFormulario.setRoundBottomRight(40);
        btnLimpiarFormulario.setRoundTopLeft(40);
        btnLimpiarFormulario.setRoundTopRight(40);
        btnLimpiarFormulario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarFormularioMouseClicked(evt);
            }
        });
        btnLimpiarFormulario.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Cuando el mouse entra, se oscurece
                btnLimpiarFormulario.setBackground(new Color(102, 102, 102));
            }
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Cuando el mouse sale, vuelve al original
                btnLimpiarFormulario.setBackground(new Color(153, 153, 153));
            }
        });
        pnlRegistroEmpleado.add(btnLimpiarFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 140, 40));

        bntRegistrarEmpleado.setBackground(new java.awt.Color(0, 204, 255));
        bntRegistrarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        bntRegistrarEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bntRegistrarEmpleado.setText("Guardar");
        bntRegistrarEmpleado.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        bntRegistrarEmpleado.setRoundBottomLeft(40);
        bntRegistrarEmpleado.setRoundBottomRight(40);
        bntRegistrarEmpleado.setRoundTopLeft(40);
        bntRegistrarEmpleado.setRoundTopRight(40);
        bntRegistrarEmpleado.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
        bntRegistrarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntRegistrarEmpleadoMouseClicked(evt);
            }
        });
        bntRegistrarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Al entrar el mouse, se aplica solo un color (puedes usar un gradiente de un solo color si tu botón lo permite)
                bntRegistrarEmpleado.setGradientHorizontal(new Color(2, 114, 185), new Color(2, 114, 185));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Al salir el mouse, se vuelve al gradiente original
                bntRegistrarEmpleado.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
            }
        });
        pnlRegistroEmpleado.add(bntRegistrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 140, 40));

        jPanel1.add(pnlRegistroEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 370, 530));

        panelMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 670));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondo_completo.png"))); // NOI18N
        panelMain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 670));

        getContentPane().add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 450, 670));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //container.setPanel(new PanelOptions(),panelContainer);
        //setDates();
    }//GEN-LAST:event_formWindowOpened

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(Color.red);
        btnExit.setForeground(Color.white);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new Color(215, 235, 255));
        btnExit.setForeground(new Color(0, 51, 153));
    }

    private void panelActionsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-LAST:event_btnExitMouseExited
        int x = getLocation().x + evt.getX() - initX;//GEN-FIRST:event_panelActionsMouseDragged
        int y = getLocation().y + evt.getY() - initY;
        this.setLocation(x, y);
    }//GEN-LAST:event_panelActionsMouseDragged

    private void panelActionsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActionsMousePressed
        initX = evt.getX();
        initY = evt.getY();
    }//GEN-LAST:event_panelActionsMousePressed

    private void bntRegistrarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntRegistrarEmpleadoMouseClicked
        int actualizar = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres actualizar?");
        if (actualizar == JOptionPane.YES_OPTION) {
            actulizarEmpleado();
        }
    }//GEN-LAST:event_bntRegistrarEmpleadoMouseClicked

    private void btnLimpiarFormularioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarFormularioMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnLimpiarFormularioMouseClicked

    private void actulizarEmpleado() {
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String cargo = txtCargo.getText();
        String rol = (String) cmbPuesto.getSelectedItem();

        empleadoActualizar.setNombre(nombre);
        empleadoActualizar.setApellido(apellido);
        empleadoActualizar.setPuesto(cargo);

        usuarioActualizar.setRol(rol);

        try {
            boolean empleadoActualizado = e.actualizarEmpleado(empleadoActualizar);
            boolean usuarioActualizado = u.actualizarUsuario(usuarioActualizar);

            if (empleadoActualizado && usuarioActualizado) {
                JOptionPane.showMessageDialog(this,
                        "Empleado actualizado con éxito");
            }

            this.dispose();

        } catch (Excepciones ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void verDatosEmpleado() {
        try {
            this.empleadoActualizar = e.obtenerEmpleado(empleadoId);
            this.usuarioActualizar = u.obtenerUsuarioPorEmpleadoId(empleadoId);

            txtNombre.setText(empleadoActualizar.getNombre());
            txtApellido.setText(empleadoActualizar.getApellido());
            txtCargo.setText(empleadoActualizar.getPuesto());
            cmbPuesto.setSelectedItem(usuarioActualizar.getRol());

        } catch (Excepciones ex) {
            Logger.getLogger(ActualizarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jilmar.LabelRound bntRegistrarEmpleado;
    private javax.swing.JLabel btnExit;
    private jilmar.LabelRound btnLimpiarFormulario;
    private javax.swing.JComboBox<String> cmbPuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblResumen1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelActions;
    private javax.swing.JPanel panelMain;
    private jilmar.PanelRound panelRound1;
    private jilmar.PanelRound panelRound14;
    private jilmar.PanelRound panelRound15;
    private jilmar.PanelRound panelRound16;
    private jilmar.PanelRound panelRound4;
    private jilmar.PanelRound pnlRegistroEmpleado;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
