package itin_pc.view;

import itin_pc.controller.ProductoControlador;
import itin_pc.model.Categoria;
import itin_pc.model.Marca;
import itin_pc.model.Producto;
import itin_pc.util.Excepciones;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ActualizarProducto extends javax.swing.JFrame {

    private final ProductoControlador p;


    private final int productoId;

    Producto productoActualizar;

    private int initX, initY;

    public ActualizarProducto(int productoId) {

        this.p = new ProductoControlador();

        this.productoId = productoId;

        initComponents();
        this.setLocationRelativeTo(null);
        aplicarComboBox();

        verDatosProducto();
    }

    private void aplicarComboBox() {
        try {
            List<Categoria> categorias = p.obtenerCategorias();

            cmbCategorias.removeAllItems();
            cmbCategorias.addItem(new Categoria(0, "Categorías"));

            for (Categoria categoria : categorias) {
                cmbCategorias.addItem(categoria);
            }

            List<Marca> marcas = p.obtenerMarcas();

            cmbMarcas.removeAllItems();
            cmbMarcas.addItem(new Marca(0, "Marcas"));

            for (Marca marca : marcas) {
                cmbMarcas.addItem(marca);
            }

        } catch (Excepciones ex) {
            Logger.getLogger(GestionProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActions = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelRound14 = new jilmar.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlRegistroEmpleado = new jilmar.PanelRound();
        lblResumen1 = new javax.swing.JLabel();
        panelRound4 = new jilmar.PanelRound();
        txtNombre = new javax.swing.JTextField();
        panelRound1 = new jilmar.PanelRound();
        txtStock = new javax.swing.JTextField();
        panelRound15 = new jilmar.PanelRound();
        txtDescripcion = new javax.swing.JTextField();
        panelRound16 = new jilmar.PanelRound();
        txtPrecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelRound3 = new jilmar.PanelRound();
        cmbCategorias = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        panelRound6 = new jilmar.PanelRound();
        cmbMarcas = new javax.swing.JComboBox<>();
        bntRegistrarProducto = new jilmar.LabelRound();
        btnLimpiarFormulario = new jilmar.LabelRound();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelActions.setBackground(new java.awt.Color(215, 235, 255));
        panelActions.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelActionsMouseDragged(evt);
            }
        });
        panelActions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelActionsMousePressed(evt);
            }
        });
        panelActions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_icono.png"))); // NOI18N
        panelActions.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        lblTitle.setBackground(new java.awt.Color(0, 51, 153));
        lblTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 153));
        lblTitle.setText("ITIN-PC Mundo Tecnologico");
        panelActions.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 0, -1, 30));

        btnExit.setBackground(new java.awt.Color(215, 235, 255));
        btnExit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 51, 153));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        panelActions.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 50, 30));

        getContentPane().add(panelActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 30));

        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound14.setBackground(new Color(255, 255, 255,80));
        panelRound14.setRoundBottomLeft(30);
        panelRound14.setRoundBottomRight(30);
        panelRound14.setRoundTopLeft(30);
        panelRound14.setRoundTopRight(30);
        panelRound14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_icon_50x50.png"))); // NOI18N
        panelRound14.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestion de Productos");
        panelRound14.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Administracion de Productos");
        panelRound14.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jPanel1.add(panelRound14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 370, 80));

        pnlRegistroEmpleado.setBackground(new Color(255, 255, 255, 230));
        pnlRegistroEmpleado.setRoundBottomLeft(30);
        pnlRegistroEmpleado.setRoundBottomRight(30);
        pnlRegistroEmpleado.setRoundTopLeft(30);
        pnlRegistroEmpleado.setRoundTopRight(30);
        pnlRegistroEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblResumen1.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 20)); // NOI18N
        lblResumen1.setForeground(new java.awt.Color(0, 51, 153));
        lblResumen1.setText("Registrar Nuevo Producto");
        pnlRegistroEmpleado.add(lblResumen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(15);
        panelRound4.setRoundBottomRight(15);
        panelRound4.setRoundTopLeft(15);
        panelRound4.setRoundTopRight(15);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 14)); // NOI18N
        txtNombre.setText("Mouser HP");
        txtNombre.setBorder(null);
        panelRound4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, 40));

        pnlRegistroEmpleado.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 310, 40));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(15);
        panelRound1.setRoundBottomRight(15);
        panelRound1.setRoundTopLeft(15);
        panelRound1.setRoundTopRight(15);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtStock.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 14)); // NOI18N
        txtStock.setText("10");
        txtStock.setBorder(null);
        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });
        panelRound1.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, 40));

        pnlRegistroEmpleado.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 145, 40));

        panelRound15.setBackground(new java.awt.Color(255, 255, 255));
        panelRound15.setRoundBottomLeft(15);
        panelRound15.setRoundBottomRight(15);
        panelRound15.setRoundTopLeft(15);
        panelRound15.setRoundTopRight(15);
        panelRound15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDescripcion.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 14)); // NOI18N
        txtDescripcion.setText("Mouse Inalambrico, Blootue 6.");
        txtDescripcion.setBorder(null);
        panelRound15.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, 40));

        pnlRegistroEmpleado.add(panelRound15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 310, 40));

        panelRound16.setBackground(new java.awt.Color(255, 255, 255));
        panelRound16.setRoundBottomLeft(15);
        panelRound16.setRoundBottomRight(15);
        panelRound16.setRoundTopLeft(15);
        panelRound16.setRoundTopRight(15);
        panelRound16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrecio.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 14)); // NOI18N
        txtPrecio.setText("888.99");
        txtPrecio.setBorder(null);
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        panelRound16.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, 40));

        pnlRegistroEmpleado.add(panelRound16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 145, 40));

        jLabel8.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Stock");
        pnlRegistroEmpleado.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 50, -1));

        jLabel21.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Nombre");
        pnlRegistroEmpleado.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, -1));

        jLabel23.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Descripcion");
        pnlRegistroEmpleado.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, -1));

        jLabel24.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Precio");
        pnlRegistroEmpleado.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 50, -1));

        jLabel9.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Categoria");
        pnlRegistroEmpleado.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 80, -1));

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(15);
        panelRound3.setRoundBottomRight(15);
        panelRound3.setRoundTopLeft(15);
        panelRound3.setRoundTopRight(15);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbCategorias.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 12)); // NOI18N
        cmbCategorias.setBorder(null);
        panelRound3.add(cmbCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 40));

        pnlRegistroEmpleado.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 145, 40));

        jLabel10.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Marca");
        pnlRegistroEmpleado.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 50, -1));

        panelRound6.setBackground(new java.awt.Color(255, 255, 255));
        panelRound6.setRoundBottomLeft(15);
        panelRound6.setRoundBottomRight(15);
        panelRound6.setRoundTopLeft(15);
        panelRound6.setRoundTopRight(15);
        panelRound6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbMarcas.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 12)); // NOI18N
        cmbMarcas.setBorder(null);
        panelRound6.add(cmbMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 40));

        pnlRegistroEmpleado.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 145, 40));

        bntRegistrarProducto.setBackground(new java.awt.Color(0, 204, 255));
        bntRegistrarProducto.setForeground(new java.awt.Color(255, 255, 255));
        bntRegistrarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bntRegistrarProducto.setText("Guardar");
        bntRegistrarProducto.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        bntRegistrarProducto.setRoundBottomLeft(40);
        bntRegistrarProducto.setRoundBottomRight(40);
        bntRegistrarProducto.setRoundTopLeft(40);
        bntRegistrarProducto.setRoundTopRight(40);
        bntRegistrarProducto.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
        bntRegistrarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntRegistrarProductoMouseClicked(evt);
            }
        });
        bntRegistrarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Al entrar el mouse, se aplica solo un color (puedes usar un gradiente de un solo color si tu botón lo permite)
                bntRegistrarProducto.setGradientHorizontal(new Color(2, 114, 185), new Color(2, 114, 185));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Al salir el mouse, se vuelve al gradiente original
                bntRegistrarProducto.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
            }
        });
        pnlRegistroEmpleado.add(bntRegistrarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 140, 40));

        btnLimpiarFormulario.setBackground(new java.awt.Color(153, 153, 153));
        btnLimpiarFormulario.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLimpiarFormulario.setText("Cancelar");
        btnLimpiarFormulario.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        btnLimpiarFormulario.setRoundBottomLeft(40);
        btnLimpiarFormulario.setRoundBottomRight(40);
        btnLimpiarFormulario.setRoundTopLeft(40);
        btnLimpiarFormulario.setRoundTopRight(40);
        btnLimpiarFormulario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarFormularioMouseClicked(evt);
            }
        });
        btnLimpiarFormulario.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Cuando el mouse entra, se oscurece
                btnLimpiarFormulario.setBackground(new Color(102, 102, 102));
            }
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Cuando el mouse sale, vuelve al original
                btnLimpiarFormulario.setBackground(new Color(153, 153, 153));
            }
        });
        pnlRegistroEmpleado.add(btnLimpiarFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 140, 40));

        jPanel1.add(pnlRegistroEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 370, 530));

        panelMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 670));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondo_completo.png"))); // NOI18N
        panelMain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 670));

        getContentPane().add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 450, 670));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //container.setPanel(new PanelOptions(),panelContainer);
        //setDates();
    }//GEN-LAST:event_formWindowOpened

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(Color.red);
        btnExit.setForeground(Color.white);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new Color(215, 235, 255));
        btnExit.setForeground(new Color(0, 51, 153));
    }

    private void panelActionsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-LAST:event_btnExitMouseExited
        int x = getLocation().x + evt.getX() - initX;//GEN-FIRST:event_panelActionsMouseDragged
        int y = getLocation().y + evt.getY() - initY;
        this.setLocation(x, y);
    }//GEN-LAST:event_panelActionsMouseDragged

    private void panelActionsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActionsMousePressed
        initX = evt.getX();
        initY = evt.getY();
    }//GEN-LAST:event_panelActionsMousePressed

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtStockKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void bntRegistrarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntRegistrarProductoMouseClicked
        actulizarProducto();
    }//GEN-LAST:event_bntRegistrarProductoMouseClicked

    private void btnLimpiarFormularioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarFormularioMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnLimpiarFormularioMouseClicked

    private void actulizarProducto() {
    String nombre = txtNombre.getText();
    String descripcion = txtDescripcion.getText();
    double precio = Double.parseDouble(txtPrecio.getText());
    int stock = Integer.parseInt(txtStock.getText());
    int categoriaId = ((Categoria) cmbCategorias.getSelectedItem()).getId();
    int marcaId = ((Marca) cmbMarcas.getSelectedItem()).getId();

    productoActualizar.setNombre(nombre);
    productoActualizar.setDescripcion(descripcion);
    productoActualizar.setPrecio(precio);
    productoActualizar.setCategoriaId(categoriaId);
    productoActualizar.setMarcaId(marcaId);

    try {
        boolean actualizado = p.actualizarProducto(productoActualizar, stock);

        if (actualizado) {
            JOptionPane.showMessageDialog(this, 
                "Producto actualizado exitosamente.");
        } else {
            JOptionPane.showMessageDialog(this, 
                "No se pudo actualizar el producto. Verifica los datos.");
        }

    } catch (Excepciones ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
}

    private void verDatosProducto() {
        try {
            productoActualizar = p.obtenerProductoPorId(productoId);

            txtNombre.setText(productoActualizar.getNombre());
            txtDescripcion.setText(productoActualizar.getDescripcion());
            txtPrecio.setText(String.valueOf(productoActualizar.getPrecio()));
            txtStock.setText(String.valueOf(p.obtenerStockPorProductoId(productoId)));

            Marca marcaSeleccionada = obtenerMarca(productoActualizar.getMarcaId());
            cmbMarcas.setSelectedItem(marcaSeleccionada);
            Categoria categoriaSeleccionanda = obtenerCategoria(productoActualizar.getCategoriaId());
            cmbCategorias.setSelectedItem(categoriaSeleccionanda);
            
        } catch (Excepciones ex) {
            Logger.getLogger(GestionProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private Categoria obtenerCategoria(int categoriaId) {
        try {
            List<Categoria> categorias = p.obtenerCategorias();
            for (Categoria categoria : categorias) {
                if (categoria.getId() == categoriaId) {
                    return categoria;
                }
            }
        } catch (Excepciones ex) {
            Logger.getLogger(GestionProductos.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }

    private Marca obtenerMarca(int marcaId) {
        try {
            List<Marca> marcas = p.obtenerMarcas();
            for (Marca marca : marcas) {
                if (marca.getId() == marcaId) {
                    return marca;
                }
            }
        } catch (Excepciones ex) {
            Logger.getLogger(GestionProductos.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jilmar.LabelRound bntRegistrarProducto;
    private javax.swing.JLabel btnExit;
    private jilmar.LabelRound btnLimpiarFormulario;
    private javax.swing.JComboBox<Categoria> cmbCategorias;
    private javax.swing.JComboBox<Marca> cmbMarcas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblResumen1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelActions;
    private javax.swing.JPanel panelMain;
    private jilmar.PanelRound panelRound1;
    private jilmar.PanelRound panelRound14;
    private jilmar.PanelRound panelRound15;
    private jilmar.PanelRound panelRound16;
    private jilmar.PanelRound panelRound3;
    private jilmar.PanelRound panelRound4;
    private jilmar.PanelRound panelRound6;
    private jilmar.PanelRound pnlRegistroEmpleado;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

}
