package itin_pc.view;

import itin_pc.controller.ClienteControlador;
import itin_pc.controller.EmpleadoControlador;
import itin_pc.model.Categoria;
import itin_pc.model.Cliente;
import itin_pc.model.Empleado;
import itin_pc.model.TipoCliente;
import itin_pc.model.Usuario;
import itin_pc.util.Excepciones;
import itin_pc.util.SesionUsuario;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.BorderFactory;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import jilmar.LabelRound;

public class GestionClientes extends javax.swing.JFrame {

    private DefaultTableModel modeloTabla;

    private final EmpleadoControlador e;
    private final ClienteControlador c;

    List<Cliente> listaClientesBD;
    List<Cliente> listaClientesFiltrados;
    List<TipoCliente> tipoCliente;

    Usuario usuario;
    Empleado empleado;

    private int initX, initY;
    private boolean bandera = true;

    public GestionClientes() {

        this.e = new EmpleadoControlador();
        this.c = new ClienteControlador();

        this.usuario = SesionUsuario.obtenerUsuarioActual();

        initComponents();
        this.setLocationRelativeTo(null);
        aplicarComboBox();

        this.bandera = false;

        propiedadTabla();

        configuracionRol();

        verTodosLosClientes();
    }

    private void configuracionRol() {
        try {
            this.empleado = e.obtenerEmpleado(usuario.getId());

            String rol = usuario.getRol();
            String nombre = empleado.getNombre() + " " + empleado.getApellido();

            lblUser.setText(nombre);
            lblRol.setText(rol);

        } catch (Excepciones ex) {
            Logger.getLogger(GestionClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void aplicarComboBox() {
        try {
            tipoCliente = c.obtenerTiposCliente();

            cmbTipoCliente.removeAllItems();
            cmbTipoCliente.addItem(new TipoCliente(0, "Tipo Cliente"));

            cmbFiltro.removeAllItems();
            cmbFiltro.addItem(new TipoCliente(0, "Tipo Cliente"));

            for (TipoCliente tc : tipoCliente) {
                cmbTipoCliente.addItem(tc);
                cmbFiltro.addItem(tc);
            }

        } catch (Excepciones ex) {
            Logger.getLogger(GestionClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelRound14 = new jilmar.PanelRound();
        lblRol = new jilmar.LabelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnVolverMenu = new jilmar.LabelRound();
        pnlRegistroEmpleado = new jilmar.PanelRound();
        lblResumen1 = new javax.swing.JLabel();
        panelRound4 = new jilmar.PanelRound();
        txtNombre = new javax.swing.JTextField();
        panelRound1 = new jilmar.PanelRound();
        txtApellido = new javax.swing.JTextField();
        panelRound15 = new jilmar.PanelRound();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelRound3 = new jilmar.PanelRound();
        cmbTipoCliente = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        panelRound6 = new jilmar.PanelRound();
        txtTelefono = new javax.swing.JTextField();
        bntRegistrarCliente = new jilmar.LabelRound();
        btnLimpiarFormulario = new jilmar.LabelRound();
        pnlListaEmpleados = new jilmar.PanelRound();
        lblAccesos = new javax.swing.JLabel();
        panelRound2 = new jilmar.PanelRound();
        cmbFiltro = new javax.swing.JComboBox<>();
        panelRound5 = new jilmar.PanelRound();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new jilmar.LabelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnReportes = new jilmar.LabelRound();
        jLabel1 = new javax.swing.JLabel();
        panelActions = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound14.setBackground(new Color(255, 255, 255,80));
        panelRound14.setRoundBottomLeft(30);
        panelRound14.setRoundBottomRight(30);
        panelRound14.setRoundTopLeft(30);
        panelRound14.setRoundTopRight(30);
        panelRound14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRol.setBackground(new java.awt.Color(153, 255, 153));
        lblRol.setForeground(new java.awt.Color(0, 51, 153));
        lblRol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRol.setText("VENDEDOR");
        lblRol.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        lblRol.setRoundBottomLeft(30);
        lblRol.setRoundBottomRight(30);
        lblRol.setRoundTopLeft(30);
        lblRol.setRoundTopRight(30);
        panelRound14.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 25, 90, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_icon_50x50.png"))); // NOI18N
        panelRound14.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 15, 50, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestion de Clientes");
        panelRound14.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 15, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Administracion de clientes");
        panelRound14.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 45, -1, -1));

        lblUser.setFont(new java.awt.Font("JetBrains Mono NL ExtraBold", 0, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Jilmar Gonzalez");
        panelRound14.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        jLabel22.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Usuario:");
        panelRound14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        btnVolverMenu.setBackground(new java.awt.Color(11, 61, 120));
        btnVolverMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolverMenu.setText("Volver al Menu");
        btnVolverMenu.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        btnVolverMenu.setRoundBottomLeft(50);
        btnVolverMenu.setRoundBottomRight(50);
        btnVolverMenu.setRoundTopLeft(50);
        btnVolverMenu.setRoundTopRight(50);
        btnVolverMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMenuMouseExited(evt);
            }
        });
        panelRound14.add(btnVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 170, 40));

        jPanel1.add(panelRound14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1140, 80));

        pnlRegistroEmpleado.setBackground(new Color(255, 255, 255, 230));
        pnlRegistroEmpleado.setRoundBottomLeft(30);
        pnlRegistroEmpleado.setRoundBottomRight(30);
        pnlRegistroEmpleado.setRoundTopLeft(30);
        pnlRegistroEmpleado.setRoundTopRight(30);
        pnlRegistroEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblResumen1.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 20)); // NOI18N
        lblResumen1.setForeground(new java.awt.Color(0, 51, 153));
        lblResumen1.setText("Registrar Nuevo Cliente");
        pnlRegistroEmpleado.add(lblResumen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(15);
        panelRound4.setRoundBottomRight(15);
        panelRound4.setRoundTopLeft(15);
        panelRound4.setRoundTopRight(15);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 14)); // NOI18N
        txtNombre.setText("Jose");
        txtNombre.setBorder(null);
        panelRound4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, 40));

        pnlRegistroEmpleado.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 140, 40));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(15);
        panelRound1.setRoundBottomRight(15);
        panelRound1.setRoundTopLeft(15);
        panelRound1.setRoundTopRight(15);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApellido.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 14)); // NOI18N
        txtApellido.setText("Flores");
        txtApellido.setBorder(null);
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        panelRound1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, 40));

        pnlRegistroEmpleado.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 145, 40));

        panelRound15.setBackground(new java.awt.Color(255, 255, 255));
        panelRound15.setRoundBottomLeft(15);
        panelRound15.setRoundBottomRight(15);
        panelRound15.setRoundTopLeft(15);
        panelRound15.setRoundTopRight(15);
        panelRound15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 14)); // NOI18N
        txtEmail.setText("jose_flores@hotmail.com");
        txtEmail.setBorder(null);
        panelRound15.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, 40));

        pnlRegistroEmpleado.add(panelRound15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 310, 40));

        jLabel8.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Apellido");
        pnlRegistroEmpleado.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 80, -1));

        jLabel21.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Nombre");
        pnlRegistroEmpleado.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, -1));

        jLabel23.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Correo electronico");
        pnlRegistroEmpleado.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 150, -1));

        jLabel9.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tipo Cliente");
        pnlRegistroEmpleado.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 110, -1));

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(15);
        panelRound3.setRoundBottomRight(15);
        panelRound3.setRoundTopLeft(15);
        panelRound3.setRoundTopRight(15);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbTipoCliente.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 12)); // NOI18N
        cmbTipoCliente.setBorder(null);
        panelRound3.add(cmbTipoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 40));

        pnlRegistroEmpleado.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 300, 145, 40));

        jLabel10.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Telefono");
        pnlRegistroEmpleado.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 70, -1));

        panelRound6.setBackground(new java.awt.Color(255, 255, 255));
        panelRound6.setRoundBottomLeft(15);
        panelRound6.setRoundBottomRight(15);
        panelRound6.setRoundTopLeft(15);
        panelRound6.setRoundTopRight(15);
        panelRound6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTelefono.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 14)); // NOI18N
        txtTelefono.setText("0965215423");
        txtTelefono.setBorder(null);
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        panelRound6.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, 40));

        pnlRegistroEmpleado.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 145, 40));

        bntRegistrarCliente.setBackground(new java.awt.Color(0, 204, 255));
        bntRegistrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        bntRegistrarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bntRegistrarCliente.setText("Guardar");
        bntRegistrarCliente.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        bntRegistrarCliente.setRoundBottomLeft(40);
        bntRegistrarCliente.setRoundBottomRight(40);
        bntRegistrarCliente.setRoundTopLeft(40);
        bntRegistrarCliente.setRoundTopRight(40);
        bntRegistrarCliente.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
        bntRegistrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntRegistrarClienteMouseClicked(evt);
            }
        });
        bntRegistrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Al entrar el mouse, se aplica solo un color (puedes usar un gradiente de un solo color si tu botón lo permite)
                bntRegistrarCliente.setGradientHorizontal(new Color(4, 178, 234), new Color(4, 178, 234));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Al salir el mouse, se vuelve al gradiente original
                bntRegistrarCliente.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
            }
        });
        pnlRegistroEmpleado.add(bntRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 140, 40));

        btnLimpiarFormulario.setBackground(new java.awt.Color(153, 153, 153));
        btnLimpiarFormulario.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLimpiarFormulario.setText("Limpiar");
        btnLimpiarFormulario.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        btnLimpiarFormulario.setRoundBottomLeft(40);
        btnLimpiarFormulario.setRoundBottomRight(40);
        btnLimpiarFormulario.setRoundTopLeft(40);
        btnLimpiarFormulario.setRoundTopRight(40);
        btnLimpiarFormulario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarFormularioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarFormularioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarFormularioMouseExited(evt);
            }
        });
        pnlRegistroEmpleado.add(btnLimpiarFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 140, 40));

        jPanel1.add(pnlRegistroEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 370, 530));

        pnlListaEmpleados.setBackground(new Color(255, 255, 255, 230));
        pnlListaEmpleados.setRoundBottomLeft(30);
        pnlListaEmpleados.setRoundBottomRight(30);
        pnlListaEmpleados.setRoundTopLeft(30);
        pnlListaEmpleados.setRoundTopRight(30);
        pnlListaEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAccesos.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 20)); // NOI18N
        lblAccesos.setForeground(new java.awt.Color(0, 51, 153));
        lblAccesos.setText("Clientes Registrados");
        pnlListaEmpleados.add(lblAccesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(15);
        panelRound2.setRoundBottomRight(15);
        panelRound2.setRoundTopLeft(15);
        panelRound2.setRoundTopRight(15);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbFiltro.setBorder(null);
        cmbFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbFiltroMouseClicked(evt);
            }
        });
        cmbFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFiltroActionPerformed(evt);
            }
        });
        panelRound2.add(cmbFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, 140, 40));

        pnlListaEmpleados.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, 40));

        panelRound5.setBackground(new java.awt.Color(255, 255, 255));
        panelRound5.setRoundBottomLeft(15);
        panelRound5.setRoundBottomRight(15);
        panelRound5.setRoundTopLeft(15);
        panelRound5.setRoundTopRight(15);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(102, 102, 102));
        txtBuscar.setText("Buscar por nombre...");
        txtBuscar.setBorder(null);
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtBuscar.getText().equals("Buscar por nombre...")) {
                    txtBuscar.setText("");
                    txtBuscar.setForeground(Color.BLACK);
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtBuscar.getText().isEmpty()) {
                    txtBuscar.setText("Buscar por nombre...");
                    txtBuscar.setForeground(Color.GRAY);
                }
            }
        });
        panelRound5.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        pnlListaEmpleados.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 180, 40));

        btnBuscar.setBackground(new java.awt.Color(0, 204, 255));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setText("Buscar");
        btnBuscar.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        btnBuscar.setRoundBottomLeft(40);
        btnBuscar.setRoundBottomRight(40);
        btnBuscar.setRoundTopLeft(40);
        btnBuscar.setRoundTopRight(40);
        bntRegistrarCliente.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        pnlListaEmpleados.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 130, 40));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Usuario", "Rol", "Fecha Ingreso", "Aciones"
            }
        ));
        tblClientes.setEnabled(false);
        tblClientes.setOpaque(false);
        jScrollPane1.setViewportView(tblClientes);
        if (tblClientes.getColumnModel().getColumnCount() > 0) {
            tblClientes.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        pnlListaEmpleados.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 690, 290));

        btnReportes.setBackground(new java.awt.Color(0, 204, 255));
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReportes.setText("Reporte Clientes");
        btnReportes.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        btnReportes.setRoundBottomLeft(40);
        btnReportes.setRoundBottomRight(40);
        btnReportes.setRoundTopLeft(40);
        btnReportes.setRoundTopRight(40);
        btnReportes.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportesMouseClicked(evt);
            }
        });
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Al entrar el mouse, se aplica solo un color (puedes usar un gradiente de un solo color si tu botón lo permite)
                btnReportes.setGradientHorizontal(new Color(2, 114, 185), new Color(2, 114, 185));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Al salir el mouse, se vuelve al gradiente original
                btnReportes.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
            }
        });
        pnlListaEmpleados.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 180, 40));

        jPanel1.add(pnlListaEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 750, 530));

        panelMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 670));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondo_completo.png"))); // NOI18N
        panelMain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 670));

        getContentPane().add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1220, 670));

        panelActions.setBackground(new java.awt.Color(215, 235, 255));
        panelActions.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelActionsMouseDragged(evt);
            }
        });
        panelActions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelActionsMousePressed(evt);
            }
        });
        panelActions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_icono.png"))); // NOI18N
        panelActions.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        lblTitle.setBackground(new java.awt.Color(0, 51, 153));
        lblTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 153));
        lblTitle.setText("ITIN-PC Mundo Tecnologico");
        panelActions.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 0, -1, 30));

        btnMinimize.setBackground(new java.awt.Color(215, 235, 255));
        btnMinimize.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMinimize.setForeground(new java.awt.Color(0, 51, 153));
        btnMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize.setText("-");
        btnMinimize.setOpaque(true);
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        panelActions.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 50, 30));

        btnExit.setBackground(new java.awt.Color(215, 235, 255));
        btnExit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 51, 153));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        panelActions.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 50, 30));

        getContentPane().add(panelActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 30));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setBackground(Color.gray);
        btnMinimize.setForeground(Color.white);
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        btnMinimize.setBackground(new Color(215, 235, 255));
        btnMinimize.setForeground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(Color.red);
        btnExit.setForeground(Color.white);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new Color(215, 235, 255));
        btnExit.setForeground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnExitMouseExited

    private void panelActionsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActionsMouseDragged
        int x = getLocation().x + evt.getX() - initX;
        int y = getLocation().y + evt.getY() - initY;
        this.setLocation(x, y);
    }//GEN-LAST:event_panelActionsMouseDragged

    private void panelActionsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActionsMousePressed
        initX = evt.getX();
        initY = evt.getY();
    }//GEN-LAST:event_panelActionsMousePressed

    private void btnVolverMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMenuMouseClicked
        new MenuPrincipal(SesionUsuario.obtenerUsuarioActual()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverMenuMouseClicked

    private void btnVolverMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMenuMouseEntered
        btnVolverMenu.setBackground(new Color(4, 177, 233));
    }//GEN-LAST:event_btnVolverMenuMouseEntered

    private void btnVolverMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMenuMouseExited
        btnVolverMenu.setBackground(new Color(11, 61, 120));
    }//GEN-LAST:event_btnVolverMenuMouseExited

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped

    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void bntRegistrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntRegistrarClienteMouseClicked
        agregarCliente();
    }//GEN-LAST:event_bntRegistrarClienteMouseClicked

    private void btnLimpiarFormularioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarFormularioMouseClicked
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarFormularioMouseClicked

    private void btnLimpiarFormularioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarFormularioMouseEntered
        btnLimpiarFormulario.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnLimpiarFormularioMouseEntered

    private void btnLimpiarFormularioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarFormularioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarFormularioMouseExited

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        aplicarFiltros();
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        aplicarFiltros();
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void cmbFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFiltroActionPerformed
       if(!bandera) aplicarFiltros(); 
    }//GEN-LAST:event_cmbFiltroActionPerformed

    private void cmbFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbFiltroMouseClicked
        txtBuscar.setText("Buscar por nombre...");
    }//GEN-LAST:event_cmbFiltroMouseClicked

    private void btnReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseClicked
        new ReportesCliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReportesMouseClicked

    private void agregarCliente() {
        String nombre = txtNombre.getText();
        String apellido = txtNombre.getText();
        String email = txtEmail.getText();
        String telefono = txtTelefono.getText();
        int tipoClienteId = ((Categoria) cmbTipoCliente.getSelectedItem()).getId();

        Cliente cliente = new Cliente(nombre, apellido, email, telefono, tipoClienteId);

        try {
            int clienteId = c.agregarCliente(cliente);

            if (clienteId > 0) {
                JOptionPane.showMessageDialog(this, "Producto registrado exitosamente.");
            }

            limpiarFormulario();

        } catch (Excepciones ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void limpiarFormulario() {
        txtNombre.setText("");
        txtEmail.setText("");
        txtTelefono.setText("");
        txtApellido.setText("");
        cmbTipoCliente.setSelectedIndex(0);
    }

    private void aplicarFiltros() {

        String filtroNombreInput = txtBuscar.getText();
        int filtro = ((TipoCliente) cmbFiltro.getSelectedItem()).getId();

        final String filtroNombre
                = (filtroNombreInput.equals("Buscar por nombre...") || filtroNombreInput.isEmpty())
                ? ""
                : filtroNombreInput.trim();

        if (!filtroNombre.isEmpty()) {
            listaClientesFiltrados = listaClientesBD.stream()
                    .filter(c -> c.getNombre().toLowerCase().contains(filtroNombre.toLowerCase()))
                    .collect(Collectors.toList());
        } else if (filtro > 0) {
            listaClientesFiltrados = listaClientesBD.stream()
                    .filter(c -> c.getTipoClienteId() == filtro)
                    .collect(Collectors.toList());
        } else {
            listaClientesFiltrados = new ArrayList<>(listaClientesBD);
        }

        if (!listaClientesFiltrados.isEmpty()) {
            actualizarTabla();
        }
    }

    private void reiniciarFiltros() {
        txtBuscar.setText("Buscar por nombre...");
        txtBuscar.setForeground(Color.GRAY);
    }

    private void verTodosLosClientes() {
        try {
            listaClientesBD = new ArrayList<>(c.obtenerClientes());
            listaClientesFiltrados = new ArrayList<>(listaClientesBD);
            actualizarTabla();
        } catch (Excepciones ex) {
            Logger.getLogger(GestionClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void actualizarTabla() {
        modeloTabla.setRowCount(0);
        for (Cliente cliente : listaClientesFiltrados) {
            Object[] fila = {
                cliente.getId(),
                cliente.getNombre() + " " + cliente.getApellido(),
                cliente.getTelefono(),
                cliente.getCorreo(),
                tipoCliente(cliente.getTipoClienteId())
            };
            modeloTabla.addRow(fila);
        }
        tblClientes.setModel(modeloTabla);
    }

    private String tipoCliente(int tipoClienteId) {
        try {
            List<TipoCliente> tipoClientes = c.obtenerTiposCliente();
            for (TipoCliente tc : tipoClientes) {
                if (tc.getId() == tipoClienteId) {
                    return tc.getTipo();
                }
            }
        } catch (Excepciones e) {
            Logger.getLogger(GestionClientes.class.getName()).log(Level.SEVERE, null, e);
        }

        return "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jilmar.LabelRound bntRegistrarCliente;
    private jilmar.LabelRound btnBuscar;
    private javax.swing.JLabel btnExit;
    private jilmar.LabelRound btnLimpiarFormulario;
    private javax.swing.JLabel btnMinimize;
    private jilmar.LabelRound btnReportes;
    private jilmar.LabelRound btnVolverMenu;
    private javax.swing.JComboBox<TipoCliente> cmbFiltro;
    private javax.swing.JComboBox<TipoCliente> cmbTipoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAccesos;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblResumen1;
    private jilmar.LabelRound lblRol;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel panelActions;
    private javax.swing.JPanel panelMain;
    private jilmar.PanelRound panelRound1;
    private jilmar.PanelRound panelRound14;
    private jilmar.PanelRound panelRound15;
    private jilmar.PanelRound panelRound2;
    private jilmar.PanelRound panelRound3;
    private jilmar.PanelRound panelRound4;
    private jilmar.PanelRound panelRound5;
    private jilmar.PanelRound panelRound6;
    private jilmar.PanelRound pnlListaEmpleados;
    private jilmar.PanelRound pnlRegistroEmpleado;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    // Propiedasdes de la tabla
    private void propiedadTabla() {
        String[] columnas = {"ID", "Nombre", "telefono", "Correo", "Tipo Cliente", "Acciones"};
        modeloTabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 5; // Solo la columna de acciones es "editable"
            }
        };

        tblClientes = new JTable(modeloTabla);
        tblClientes.setRowHeight(36);
        tblClientes.setFont(new java.awt.Font("JetBrains Mono SemiBoldd", 0, 12));
        tblClientes.getTableHeader().setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 12));
        tblClientes.getTableHeader().setBackground(new Color(4, 178, 234));
        tblClientes.getTableHeader().setForeground(Color.white);
        tblClientes.getTableHeader().setPreferredSize(new Dimension(100, 36));

        jScrollPane1.setViewportView(tblClientes);

        // Configurar el ancho de las columnas
        if (tblClientes.getColumnModel().getColumnCount() > 0) {
            tblClientes.getColumnModel().getColumn(0).setPreferredWidth(2);
            tblClientes.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblClientes.getColumnModel().getColumn(2).setPreferredWidth(40);
            tblClientes.getColumnModel().getColumn(3).setPreferredWidth(70);
            tblClientes.getColumnModel().getColumn(4).setPreferredWidth(35);
            tblClientes.getColumnModel().getColumn(5).setPreferredWidth(120);
        }

        // Agregar renderer personalizado para la columna de rol
        tblClientes.getColumnModel().getColumn(2).setCellRenderer(new RolCellRenderer());

        // Agregar renderer y editor personalizado para la columna de acciones
        tblClientes.getColumnModel().getColumn(5).setCellRenderer(new AccionesCellRenderer());
        tblClientes.getColumnModel().getColumn(5).setCellEditor(new AccionesCellEditor());

        // Centrar el texto de las celdas
        tblClientes.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (c instanceof JLabel) {
                    JLabel label = (JLabel) c;
                    label.setHorizontalAlignment(SwingConstants.CENTER);
                    label.setVerticalAlignment(SwingConstants.CENTER);
                    label.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 12)); // <-- fuerza la fuente

                }
                return c;
            }
        });

        jScrollPane1.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));

    }

    // Renderer personalizado para la columna de rol con colores
    class RolCellRenderer extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus,
                int row, int column) {
            super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            String rol = value.toString();
            setHorizontalAlignment(SwingConstants.CENTER);
            setOpaque(true);

            if (!isSelected) {
                switch (rol) {
                    case "ADMIN" -> {
                        setBackground(new Color(144, 238, 144)); // Verde claro
                        setForeground(Color.BLACK);
                    }
                    case "VENDEDOR" -> {
                        setBackground(new Color(173, 216, 230)); // Azul claro
                        setForeground(Color.BLACK);
                    }
                    case "TECNICO" -> {
                        setBackground(new Color(255, 218, 185)); // Naranja claro
                        setForeground(Color.BLACK);
                    }
                    default -> {
                        setBackground(Color.WHITE);
                        setForeground(Color.BLACK);
                    }
                }
            }

            return this;
        }
    }

    // Renderer para los botones de acciones
    class AccionesCellRenderer extends JPanel implements javax.swing.table.TableCellRenderer {

        private final LabelRound btnEditar;
        private final LabelRound btnEliminar;

        public AccionesCellRenderer() {
            setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));

            btnEditar = new LabelRound();
            btnEditar.setText("Editar");
            btnEditar.setBackground(new Color(100, 100, 200));
            btnEditar.setForeground(Color.WHITE);
            btnEditar.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 12));
            btnEditar.setPreferredSize(new Dimension(70, 25));
            btnEditar.setHorizontalAlignment(SwingConstants.CENTER);
            btnEditar.setOpaque(true);

            btnEliminar = new LabelRound();
            btnEliminar.setText("Eliminar");
            btnEliminar.setBackground(new Color(220, 53, 69));
            btnEliminar.setForeground(Color.WHITE);
            btnEliminar.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 12));
            btnEliminar.setPreferredSize(new Dimension(70, 25));
            btnEliminar.setHorizontalAlignment(SwingConstants.CENTER);
            btnEliminar.setOpaque(true);

            add(btnEditar);
            add(btnEliminar);
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus,
                int row, int column) {
            if (isSelected) {
                setBackground(table.getSelectionBackground());
            } else {
                setBackground(table.getBackground());
            }
            return this;
        }
    }

    // Editor para los botones de acciones
    class AccionesCellEditor extends DefaultCellEditor {

        private final JPanel panel;
        private LabelRound btnEditar;
        private LabelRound btnEliminar;

        public AccionesCellEditor() {

            super(new JCheckBox());

            panel = new JPanel(new FlowLayout(FlowLayout.CENTER, 5, 5));

            btnEditar = new LabelRound();
            btnEditar.setText("Editar");
            btnEditar.setBackground(new Color(100, 100, 200));
            btnEditar.setForeground(Color.WHITE);
            btnEditar.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 12));
            btnEditar.setPreferredSize(new Dimension(70, 25));
            btnEditar.setHorizontalAlignment(SwingConstants.CENTER);
            btnEditar.setOpaque(true);
            btnEditar.setCursor(new Cursor(Cursor.HAND_CURSOR));

            btnEliminar = new LabelRound();
            btnEliminar.setText("Eliminar");
            btnEliminar.setBackground(new Color(220, 53, 69));
            btnEliminar.setForeground(Color.WHITE);
            btnEliminar.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 12));
            btnEliminar.setPreferredSize(new Dimension(70, 25));
            btnEliminar.setHorizontalAlignment(SwingConstants.CENTER);
            btnEliminar.setOpaque(true);
            btnEliminar.setCursor(new Cursor(Cursor.HAND_CURSOR));

            btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    // editarEmpleado(filaActual);
                    fireEditingStopped();
                }

                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    btnEditar.setBackground(new Color(80, 80, 180));
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    btnEditar.setBackground(new Color(100, 100, 200));
                }
            });

            btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    // new Plantilla().setVisible(true);
                    fireEditingStopped();
                }

                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    btnEliminar.setBackground(new Color(200, 33, 49));
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    btnEliminar.setBackground(new Color(220, 53, 69));
                }
            });

            panel.add(btnEditar);
            panel.add(btnEliminar);
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row,
                int column) {
            table.convertRowIndexToModel(row);
            return panel;
        }

        @Override
        public Object getCellEditorValue() {
            return "Acciones";
        }
    }

}
