package itin_pc.view;

import itin_pc.controller.AutenticacionControlador;
import itin_pc.seguridad.Autorizacion;
import itin_pc.util.Excepciones;
import itin_pc.util.SesionUsuario;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    public static String user;
    public static String pass;

    private AutenticacionControlador autenticacion;

    private int initX, initY;

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);

        autenticacion = new AutenticacionControlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActions = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        panelLogin = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        pnlUser = new ComponentRoundJilmar.PanelRound();
        icon_user = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        pnlPass = new ComponentRoundJilmar.PanelRound();
        icon_pass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btnSesion = new ComponentRoundJilmar.LabelRound();
        linkNewAccount = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelFondo = new javax.swing.JLabel();
        panelLogo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelActions.setBackground(new java.awt.Color(215, 235, 255));
        panelActions.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelActionsMouseDragged(evt);
            }
        });
        panelActions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelActionsMousePressed(evt);
            }
        });
        panelActions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_icono.png"))); // NOI18N
        panelActions.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        lblTitle.setBackground(new java.awt.Color(0, 51, 153));
        lblTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 153));
        lblTitle.setText("ITIN-PC Mundo Tecnologico");
        panelActions.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 0, -1, 30));

        btnMinimize.setBackground(new java.awt.Color(215, 235, 255));
        btnMinimize.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMinimize.setForeground(new java.awt.Color(0, 51, 153));
        btnMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize.setText("-");
        btnMinimize.setOpaque(true);
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        panelActions.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 50, 30));

        btnExit.setBackground(new java.awt.Color(215, 235, 255));
        btnExit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 51, 153));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        panelActions.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 50, 30));

        getContentPane().add(panelActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 30));

        panelLogin.setPreferredSize(new java.awt.Dimension(660, 670));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDatos.setOpaque(false);
        panelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Usuario");
        panelDatos.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        pnlUser.setBackground(new java.awt.Color(255, 255, 255));
        pnlUser.setRoundBottomLeft(50);
        pnlUser.setRoundBottomRight(50);
        pnlUser.setRoundTopLeft(50);
        pnlUser.setRoundTopRight(50);
        pnlUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuario_icono.png"))); // NOI18N
        pnlUser.add(icon_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 30));

        txtUser.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtUser.setText("jigonzalez17");
        txtUser.setBorder(null);
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserKeyTyped(evt);
            }
        });
        pnlUser.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 330, 30));

        panelDatos.add(pnlUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 430, 50));

        lblPass.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPass.setForeground(new java.awt.Color(255, 255, 255));
        lblPass.setText("Contraseña");
        panelDatos.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        pnlPass.setBackground(new java.awt.Color(255, 255, 255));
        pnlPass.setRoundBottomLeft(50);
        pnlPass.setRoundBottomRight(50);
        pnlPass.setRoundTopLeft(50);
        pnlPass.setRoundTopRight(50);
        pnlPass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/seguridad_icono.png"))); // NOI18N
        pnlPass.add(icon_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 30));

        txtPass.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtPass.setText("1752597953Jilmar");
        txtPass.setBorder(null);
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassKeyTyped(evt);
            }
        });
        pnlPass.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 310, 30));

        panelDatos.add(pnlPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 430, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido!");
        panelDatos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        btnSesion.setBackground(new java.awt.Color(11, 61, 120));
        btnSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSesion.setText("Iniciar Sesion");
        btnSesion.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnSesion.setRoundBottomLeft(50);
        btnSesion.setRoundBottomRight(50);
        btnSesion.setRoundTopLeft(50);
        btnSesion.setRoundTopRight(50);
        btnSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSesionMouseExited(evt);
            }
        });
        panelDatos.add(btnSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 180, 50));

        linkNewAccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        linkNewAccount.setForeground(new java.awt.Color(255, 255, 255));
        linkNewAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        linkNewAccount.setText("¿Olvidaste tu Contraseña?");
        linkNewAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkNewAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkNewAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkNewAccountMouseExited(evt);
            }
        });
        panelDatos.add(linkNewAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, -1, -1));

        jSeparator1.setBackground(new Color(0,0,0,0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        panelDatos.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, 140, 10));

        panelLogin.add(panelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 670));

        labelFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondo.png"))); // NOI18N
        panelLogin.add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 670));

        getContentPane().add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 660, 670));

        panelLogo.setBackground(new java.awt.Color(255, 255, 255));
        panelLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(11, 61, 120));
        jLabel2.setText("MUNDO TECNOLÓGICO");
        panelLogo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo.png"))); // NOI18N
        panelLogo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 510, 580));

        getContentPane().add(panelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 560, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(Color.red);
        btnExit.setForeground(Color.white);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setBackground(Color.gray);
        btnMinimize.setForeground(Color.white);
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new Color(215, 235, 255));
        btnExit.setForeground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        btnMinimize.setBackground(new Color(215, 235, 255));
        btnMinimize.setForeground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void panelActionsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActionsMouseDragged
        int x = getLocation().x + evt.getX() - initX;
        int y = getLocation().y + evt.getY() - initY;
        this.setLocation(x, y);
    }//GEN-LAST:event_panelActionsMouseDragged

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSesionMouseEntered
        btnSesion.setBackground(new Color(4, 177, 233));
    }//GEN-LAST:event_btnSesionMouseEntered

    private void btnSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSesionMouseExited
        btnSesion.setBackground(new Color(11, 61, 120));
    }//GEN-LAST:event_btnSesionMouseExited

    private void linkNewAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkNewAccountMouseEntered
        //action.mouseEntered(linkNewAccount, null, Color.white);
    }//GEN-LAST:event_linkNewAccountMouseEntered

    private void linkNewAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkNewAccountMouseExited
        //action.mouseEntered(linkNewAccount, null, Color.black);
    }//GEN-LAST:event_linkNewAccountMouseExited

    private void btnSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSesionMouseClicked
        btnLogin();
    }//GEN-LAST:event_btnSesionMouseClicked

    private void linkNewAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkNewAccountMouseClicked
        //new Register().setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_linkNewAccountMouseClicked

    private void txtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyTyped
        //if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
        //    btnLogin();
        //}
    }//GEN-LAST:event_txtPassKeyTyped

    private void panelActionsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActionsMousePressed
        initX = evt.getX();
        initY = evt.getY();
    }//GEN-LAST:event_panelActionsMousePressed

    private void txtUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyTyped
        //if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
        //   btnLogin();
        //}
    }//GEN-LAST:event_txtUserKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnMinimize;
    private ComponentRoundJilmar.LabelRound btnSesion;
    private javax.swing.JLabel icon_pass;
    private javax.swing.JLabel icon_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel linkNewAccount;
    private javax.swing.JPanel panelActions;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelLogo;
    private ComponentRoundJilmar.PanelRound pnlPass;
    private ComponentRoundJilmar.PanelRound pnlUser;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    // Verifican que los campos de User y Pass no esten vacios
    // Verifican si el Usuario existe en la BD
    private void btnLogin() {
        user = txtUser.getText();
        pass = String.valueOf(txtPass.getPassword());

        if (user.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Existen Compos Vacios", "Error", JOptionPane.ERROR_MESSAGE);
        }

        try {
            AutenticacionControlador.ResultadoLogin resultado = autenticacion.loginItinPC(user, pass);

            switch (resultado) {
                case ADMIN:
                    //new MenuPrincipalAdmin().setVisible(true);
                    this.dispose();
                    break;
                case VENDEDOR:
                    //new MenuPrincipalVendedor().setVisible(true);
                    this.dispose();
                    break;
                case TECNICO:
                    //new MenuPrincipalTecnico().setVisible(true);
                    this.dispose();
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Usuario o Contraseña incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Excepciones ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
