package itin_pc.view;

import itin_pc.controller.EmpleadoControlador;
import itin_pc.model.Empleado;
import itin_pc.model.Usuario;
import itin_pc.util.Excepciones;
import itin_pc.util.SesionUsuario;
import java.awt.Color;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import jilmar.PanelRound;

public class MenuPrincipal extends javax.swing.JFrame {

    private final EmpleadoControlador e;

    private final Usuario usuario;
    private Empleado empleado;

    private int usuarioId;

    private int initX, initY;

    public MenuPrincipal(Usuario usuario) {

        this.e = new EmpleadoControlador();
        this.usuario = usuario;

        initComponents();
        this.setLocationRelativeTo(null);

        configuracionRol();

    }

    private void configuracionRol() {

        try {
            this.usuarioId = usuario.getId();
            this.empleado = e.obtenerEmpleado(usuarioId);

            String rol = usuario.getRol();
            String nombre = empleado.getNombre() + " " + empleado.getApellido();

            lblUser.setText(nombre);
            lblRol.setText(rol);

            switch (rol) {
                case "VENDEDOR" -> {
                    funcionesVendedor();
                }
                case "TECNICO" -> {
                    funcionesTecnico();
                }
            }

        } catch (Excepciones ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }

    private void funcionesVendedor() {
        deshabilitarBoton(btnGestionEmpleadoss);
        //deshabilitarBoton(btnServicioTecnico);
    }

    private void funcionesTecnico() {
        deshabilitarBoton(btnGestionEmpleadoss);
    }

    private void deshabilitarBoton(PanelRound boton) {
        for (MouseListener ml : boton.getMouseListeners()) {
            boton.removeMouseListener(ml);
        }

        boton.setOpaque(false);
        boton.setBackground(new Color(0, 0, 0, 100));
        boton.setRoundBottomLeft(25);
        boton.setRoundBottomRight(25);
        boton.setRoundTopLeft(25);
        boton.setRoundTopRight(25);
        boton.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActions = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelRound14 = new jilmar.PanelRound();
        lblRol = new jilmar.LabelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCerrarSesion = new jilmar.LabelRound();
        lblUser = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        pnlResumen = new jilmar.PanelRound();
        lblResumen1 = new javax.swing.JLabel();
        panelRound4 = new jilmar.PanelRound();
        lblVentasMensules = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelRound1 = new jilmar.PanelRound();
        lblServiciosPendientes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelRound15 = new jilmar.PanelRound();
        lblProductosStock = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelRound16 = new jilmar.PanelRound();
        lblClientesVIP = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlAcceso = new jilmar.PanelRound();
        lblAccesos = new javax.swing.JLabel();
        pnlEmpleados = new javax.swing.JPanel();
        btnGestionEmpleadoss = new jilmar.PanelRound();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblStock5 = new javax.swing.JLabel();
        gradiente = new jilmar.LabelRound();
        pnlClientes = new javax.swing.JPanel();
        btnGestionClientess = new jilmar.PanelRound();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblStock9 = new javax.swing.JLabel();
        gradiente4 = new jilmar.LabelRound();
        pnlProductos = new javax.swing.JPanel();
        btnGestionProductos = new jilmar.PanelRound();
        jPanel7 = new javax.swing.JPanel();
        lblStock10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        gradiente5 = new jilmar.LabelRound();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelActions.setBackground(new java.awt.Color(215, 235, 255));
        panelActions.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelActionsMouseDragged(evt);
            }
        });
        panelActions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelActionsMousePressed(evt);
            }
        });
        panelActions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_icono.png"))); // NOI18N
        panelActions.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        lblTitle.setBackground(new java.awt.Color(0, 51, 153));
        lblTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 153));
        lblTitle.setText("ITIN-PC Mundo Tecnologico");
        panelActions.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 0, -1, 30));

        btnMinimize.setBackground(new java.awt.Color(215, 235, 255));
        btnMinimize.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMinimize.setForeground(new java.awt.Color(0, 51, 153));
        btnMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize.setText("-");
        btnMinimize.setOpaque(true);
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        panelActions.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 50, 30));

        btnExit.setBackground(new java.awt.Color(215, 235, 255));
        btnExit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 51, 153));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        panelActions.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 50, 30));

        getContentPane().add(panelActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 30));

        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound14.setBackground(new Color(255, 255, 255,80));
        panelRound14.setRoundBottomLeft(30);
        panelRound14.setRoundBottomRight(30);
        panelRound14.setRoundTopLeft(30);
        panelRound14.setRoundTopRight(30);
        panelRound14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRol.setBackground(new java.awt.Color(153, 255, 153));
        lblRol.setForeground(new java.awt.Color(0, 51, 153));
        lblRol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRol.setText("VENDEDOR");
        lblRol.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        lblRol.setRoundBottomLeft(30);
        lblRol.setRoundBottomRight(30);
        lblRol.setRoundTopLeft(30);
        lblRol.setRoundTopRight(30);
        panelRound14.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 25, 90, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_icon_50x50.png"))); // NOI18N
        panelRound14.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 15, 50, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ITIN-PC");
        panelRound14.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 15, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mundo Tecnológico");
        panelRound14.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 45, -1, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(11, 61, 120));
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        btnCerrarSesion.setRoundBottomLeft(50);
        btnCerrarSesion.setRoundBottomRight(50);
        btnCerrarSesion.setRoundTopLeft(50);
        btnCerrarSesion.setRoundTopRight(50);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });
        panelRound14.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 160, 40));

        lblUser.setFont(new java.awt.Font("JetBrains Mono NL ExtraBold", 0, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Jilmar Gonzalez");
        panelRound14.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        jLabel22.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Bienvenido:");
        panelRound14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        jPanel1.add(panelRound14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1140, 80));

        pnlResumen.setBackground(new Color(255, 255, 255, 230));
        pnlResumen.setRoundBottomLeft(30);
        pnlResumen.setRoundBottomRight(30);
        pnlResumen.setRoundTopLeft(30);
        pnlResumen.setRoundTopRight(30);
        pnlResumen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblResumen1.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 20)); // NOI18N
        lblResumen1.setForeground(new java.awt.Color(0, 51, 153));
        lblResumen1.setText("Dashboard - Resumen");
        pnlResumen.add(lblResumen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(25);
        panelRound4.setRoundBottomRight(25);
        panelRound4.setRoundTopLeft(25);
        panelRound4.setRoundTopRight(25);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVentasMensules.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 24)); // NOI18N
        lblVentasMensules.setForeground(new java.awt.Color(0, 51, 153));
        lblVentasMensules.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentasMensules.setText("21");
        panelRound4.add(lblVentasMensules, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 20, 220, 30));

        jLabel5.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ventas del Mes");
        panelRound4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 55, 220, -1));

        pnlResumen.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 220, 90));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(25);
        panelRound1.setRoundBottomRight(25);
        panelRound1.setRoundTopLeft(25);
        panelRound1.setRoundTopRight(25);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblServiciosPendientes.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 24)); // NOI18N
        lblServiciosPendientes.setForeground(new java.awt.Color(0, 51, 153));
        lblServiciosPendientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServiciosPendientes.setText("12");
        panelRound1.add(lblServiciosPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 20, 220, 30));

        jLabel6.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Servicios Pendientes");
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 220, -1));

        pnlResumen.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 220, 90));

        panelRound15.setBackground(new java.awt.Color(255, 255, 255));
        panelRound15.setRoundBottomLeft(25);
        panelRound15.setRoundBottomRight(25);
        panelRound15.setRoundTopLeft(25);
        panelRound15.setRoundTopRight(25);
        panelRound15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProductosStock.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 24)); // NOI18N
        lblProductosStock.setForeground(new java.awt.Color(0, 51, 153));
        lblProductosStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductosStock.setText("150");
        panelRound15.add(lblProductosStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 20, 220, 30));

        jLabel8.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Productos en Stock");
        panelRound15.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 55, 210, -1));

        pnlResumen.add(panelRound15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 220, 90));

        panelRound16.setBackground(new java.awt.Color(255, 255, 255));
        panelRound16.setRoundBottomLeft(25);
        panelRound16.setRoundBottomRight(25);
        panelRound16.setRoundTopLeft(25);
        panelRound16.setRoundTopRight(25);
        panelRound16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClientesVIP.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 24)); // NOI18N
        lblClientesVIP.setForeground(new java.awt.Color(0, 51, 153));
        lblClientesVIP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClientesVIP.setText("5");
        panelRound16.add(lblClientesVIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 20, 210, 30));

        jLabel7.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Clientes VIP");
        panelRound16.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 55, 210, -1));

        pnlResumen.add(panelRound16, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, 220, 90));

        jPanel1.add(pnlResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 1140, 170));

        pnlAcceso.setBackground(new Color(255, 255, 255, 230));
        pnlAcceso.setRoundBottomLeft(30);
        pnlAcceso.setRoundBottomRight(30);
        pnlAcceso.setRoundTopLeft(30);
        pnlAcceso.setRoundTopRight(30);
        pnlAcceso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAccesos.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 20)); // NOI18N
        lblAccesos.setForeground(new java.awt.Color(0, 51, 153));
        lblAccesos.setText("Acceso Rápido - Funciones Principales");
        pnlAcceso.add(lblAccesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        pnlEmpleados.setBackground(new java.awt.Color(102, 255, 102));
        pnlEmpleados.setOpaque(false);
        pnlEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGestionEmpleadoss.setBackground(new Color(255, 255, 255, 0));
        btnGestionEmpleadoss.setOpaque(true);
        btnGestionEmpleadoss.setRoundBottomLeft(25);
        btnGestionEmpleadoss.setRoundBottomRight(25);
        btnGestionEmpleadoss.setRoundTopLeft(25);
        btnGestionEmpleadoss.setRoundTopRight(25);
        btnGestionEmpleadoss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionEmpleadossMouseClicked(evt);
            }
        });

        btnGestionEmpleadoss.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Al entrar el mouse, se aplica solo un color (puedes usar un gradiente de un solo color si tu botón lo permite)
                gradiente.setGradientHorizontal(new Color(2, 114, 185), new Color(2, 114, 185));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Al salir el mouse, se vuelve al gradiente original
                gradiente.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
            }
        });

        pnlEmpleados.add(btnGestionEmpleadoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 120));

        jPanel2.setBackground(new java.awt.Color(4, 178, 234));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Gestion de Empleados");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, 300, -1));

        jLabel14.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Administrar personal y roles");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 80, 290, -1));

        lblStock5.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 24)); // NOI18N
        lblStock5.setForeground(new java.awt.Color(0, 51, 153));
        lblStock5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStock5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_icono.png"))); // NOI18N
        jPanel2.add(lblStock5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 30));

        pnlEmpleados.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 120));

        gradiente.setRoundBottomLeft(25);
        gradiente.setRoundBottomRight(25);
        gradiente.setRoundTopLeft(25);
        gradiente.setRoundTopRight(25);
        gradiente.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
        pnlEmpleados.add(gradiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 120));

        pnlAcceso.add(pnlEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 300, 120));

        pnlClientes.setBackground(new java.awt.Color(102, 255, 102));
        pnlClientes.setOpaque(false);
        pnlClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGestionClientess.setBackground(new Color(255, 255, 255, 0));
        btnGestionClientess.setOpaque(true);
        btnGestionClientess.setRoundBottomLeft(25);
        btnGestionClientess.setRoundBottomRight(25);
        btnGestionClientess.setRoundTopLeft(25);
        btnGestionClientess.setRoundTopRight(25);
        btnGestionClientess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionClientessMouseClicked(evt);
            }
        });

        btnGestionClientess.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Al entrar el mouse, se aplica solo un color (puedes usar un gradiente de un solo color si tu botón lo permite)
                gradiente4.setGradientHorizontal(new Color(2, 114, 185), new Color(2, 114, 185));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Al salir el mouse, se vuelve al gradiente original
                gradiente4.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
            }
        });

        pnlClientes.add(btnGestionClientess, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 120));

        jPanel6.setBackground(new java.awt.Color(4, 178, 234));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Gestion de Clientes");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, 300, -1));

        jLabel18.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Base de datos de clientes");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 80, 290, -1));

        lblStock9.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 24)); // NOI18N
        lblStock9.setForeground(new java.awt.Color(0, 51, 153));
        lblStock9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStock9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_icono.png"))); // NOI18N
        jPanel6.add(lblStock9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 30));

        pnlClientes.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 120));

        gradiente4.setRoundBottomLeft(25);
        gradiente4.setRoundBottomRight(25);
        gradiente4.setRoundTopLeft(25);
        gradiente4.setRoundTopRight(25);
        gradiente4.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
        pnlClientes.add(gradiente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 120));

        pnlAcceso.add(pnlClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 300, 120));

        pnlProductos.setBackground(new java.awt.Color(102, 255, 102));
        pnlProductos.setOpaque(false);
        pnlProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGestionProductos.setBackground(new Color(255, 255, 255, 0));
        btnGestionProductos.setOpaque(true);
        btnGestionProductos.setRoundBottomLeft(25);
        btnGestionProductos.setRoundBottomRight(25);
        btnGestionProductos.setRoundTopLeft(25);
        btnGestionProductos.setRoundTopRight(25);
        btnGestionProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionProductosMouseClicked(evt);
            }
        });

        btnGestionProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Al entrar el mouse, se aplica solo un color (puedes usar un gradiente de un solo color si tu botón lo permite)
                gradiente5.setGradientHorizontal(new Color(2, 114, 185), new Color(2, 114, 185));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Al salir el mouse, se vuelve al gradiente original
                gradiente5.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
            }
        });

        pnlProductos.add(btnGestionProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 120));

        jPanel7.setBackground(new java.awt.Color(4, 178, 234));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStock10.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 24)); // NOI18N
        lblStock10.setForeground(new java.awt.Color(0, 51, 153));
        lblStock10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStock10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_icono.png"))); // NOI18N
        jPanel7.add(lblStock10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 30));

        jLabel19.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Gestion de Productos");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, 300, -1));

        jLabel20.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Administracion de productos");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 80, 290, -1));

        pnlProductos.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 120));

        gradiente5.setRoundBottomLeft(25);
        gradiente5.setRoundBottomRight(25);
        gradiente5.setRoundTopLeft(25);
        gradiente5.setRoundTopRight(25);
        gradiente5.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
        pnlProductos.add(gradiente5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 120));

        pnlAcceso.add(pnlProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 300, 120));

        jPanel1.add(pnlAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 1140, 340));

        panelMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 670));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondo_completo.png"))); // NOI18N
        panelMain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 670));

        getContentPane().add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1220, 670));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setBackground(Color.gray);
        btnMinimize.setForeground(Color.white);
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        btnMinimize.setBackground(new Color(215, 235, 255));
        btnMinimize.setForeground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(Color.red);
        btnExit.setForeground(Color.white);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new Color(215, 235, 255));
        btnExit.setForeground(new Color(0, 51, 153));
    }

    private void panelActionsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-LAST:event_btnExitMouseExited
        int x = getLocation().x + evt.getX() - initX;//GEN-FIRST:event_panelActionsMouseDragged
        int y = getLocation().y + evt.getY() - initY;
        this.setLocation(x, y);
    }//GEN-LAST:event_panelActionsMouseDragged

    private void panelActionsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActionsMousePressed
        initX = evt.getX();
        initY = evt.getY();
    }//GEN-LAST:event_panelActionsMousePressed

    private void btnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseEntered
        btnCerrarSesion.setBackground(new Color(4, 177, 233));
    }//GEN-LAST:event_btnCerrarSesionMouseEntered

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited
        btnCerrarSesion.setBackground(new Color(11, 61, 120));
    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        SesionUsuario.cerrarSesion();
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void btnGestionEmpleadossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionEmpleadossMouseClicked
        new GestionEmpleados().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionEmpleadossMouseClicked

    private void btnGestionProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionProductosMouseClicked
        new GestionProductos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionProductosMouseClicked

    private void btnGestionClientessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionClientessMouseClicked
        new GestionClientes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionClientessMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jilmar.LabelRound btnCerrarSesion;
    private javax.swing.JLabel btnExit;
    private jilmar.PanelRound btnGestionClientess;
    private jilmar.PanelRound btnGestionEmpleadoss;
    private jilmar.PanelRound btnGestionProductos;
    private javax.swing.JLabel btnMinimize;
    private jilmar.LabelRound gradiente;
    private jilmar.LabelRound gradiente4;
    private jilmar.LabelRound gradiente5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblAccesos;
    private javax.swing.JLabel lblClientesVIP;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblProductosStock;
    private javax.swing.JLabel lblResumen1;
    private jilmar.LabelRound lblRol;
    private javax.swing.JLabel lblServiciosPendientes;
    private javax.swing.JLabel lblStock10;
    private javax.swing.JLabel lblStock5;
    private javax.swing.JLabel lblStock9;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblVentasMensules;
    private javax.swing.JPanel panelActions;
    private javax.swing.JPanel panelMain;
    private jilmar.PanelRound panelRound1;
    private jilmar.PanelRound panelRound14;
    private jilmar.PanelRound panelRound15;
    private jilmar.PanelRound panelRound16;
    private jilmar.PanelRound panelRound4;
    private jilmar.PanelRound pnlAcceso;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlEmpleados;
    private javax.swing.JPanel pnlProductos;
    private jilmar.PanelRound pnlResumen;
    // End of variables declaration//GEN-END:variables

}
