
package itin_pc.view;

import java.awt.Color;


public class Plantilla extends javax.swing.JFrame {

    
    public static String user;
    public static String pass;
    
    
    int initX, initY;
    
    public Plantilla() {
        initComponents();
        this.setLocationRelativeTo(null);

        
        //user = Login.user;
        //pass = Login.pass;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActions = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelActions.setBackground(new java.awt.Color(0, 0, 0));
        panelActions.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelActionsMouseDragged(evt);
            }
        });
        panelActions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelActionsMouseEntered(evt);
            }
        });
        panelActions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon.png"))); // NOI18N
        panelActions.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("ITIN-PC");
        panelActions.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 0, -1, 30));

        btnMinimize.setBackground(new java.awt.Color(0, 0, 0));
        btnMinimize.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize.setText("-");
        btnMinimize.setOpaque(true);
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        panelActions.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 50, 30));

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        panelActions.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 50, 30));

        getContentPane().add(panelActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 30));
        getContentPane().add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1220, 670));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(Color.red);
        btnExit.setForeground(Color.white);
        //evt.mouseEntered(btnExit, Color.red, Color.white);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setBackground(Color.gray);
        btnMinimize.setForeground(Color.white);
        //action.mouseEntered(btnMinimize, Color.gray, Color.white);
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(Color.black);
        btnExit.setForeground(Color.white);
        //action.mouseExit(btnExit, Color.black, Color.white);
    }//GEN-LAST:event_btnExitMouseExited

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        btnMinimize.setBackground(Color.black);
        btnMinimize.setForeground(Color.white);
        //action.mouseExit(btnMinimize, Color.black, Color.white);
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void panelActionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActionsMouseEntered
        initX = evt.getX();
        initY = evt.getY();
    }//GEN-LAST:event_panelActionsMouseEntered

    private void panelActionsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActionsMouseDragged
        int x = getLocation().x + evt.getX() - initX;
        int y = getLocation().y + evt.getY() - initY;
        this.setLocation(x, y);
    }//GEN-LAST:event_panelActionsMouseDragged

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //container.setPanel(new PanelOptions(),panelContainer);
        //setDates();
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelActions;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables

    // Establece los datos de la Cuenta Actual
    public static void setDates() {
        
    }
}
