package itin_pc.view;

import itin_pc.controller.ClienteControlador;
import itin_pc.controller.EmpleadoControlador;
import itin_pc.controller.ProductoControlador;
import itin_pc.controller.ServicioTecnicoControlador;
import itin_pc.controller.VentaControlador;
import itin_pc.model.Cliente;
import itin_pc.model.Empleado;
import itin_pc.model.TipoCliente;
import itin_pc.model.Usuario;
import itin_pc.util.Excepciones;
import itin_pc.util.SesionUsuario;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class ReportesCliente extends javax.swing.JFrame {

    private DefaultTableModel modeloTabla;

    private final EmpleadoControlador e;
    private final VentaControlador v;
    private final ProductoControlador p;
    private final ServicioTecnicoControlador stc;
    private final ClienteControlador c;

    List<Cliente> listaClientesBD;
    List<Cliente> listaClientesFiltrados;
    List<TipoCliente> tipoCliente;

    Usuario usuario;
    Empleado empleado;

    private int initX, initY;
    private boolean bandera = true;

    public ReportesCliente() {

        this.e = new EmpleadoControlador();
        this.v = new VentaControlador();
        this.p = new ProductoControlador();
        this.stc = new ServicioTecnicoControlador();
        this.c = new ClienteControlador();

        this.usuario = SesionUsuario.obtenerUsuarioActual();

        initComponents();
        this.setLocationRelativeTo(null);
        aplicarComboBox();

        this.bandera = false;

        propiedadTabla();

        configuracionRol();

        verTodosLosClientes();

    }

    private void configuracionRol() {

        try {
            this.empleado = e.obtenerEmpleado(usuario.getId());

            String rol = usuario.getRol();
            String nombre = empleado.getNombre() + " " + empleado.getApellido();

            lblUser.setText(nombre);
            lblRol.setText(rol);

        } catch (Excepciones ex) {
            Logger.getLogger(ReportesCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void aplicarComboBox() {
        try {
            tipoCliente = c.obtenerTiposCliente();

            cmbTipoCliente.removeAllItems();
            cmbTipoCliente.addItem(new TipoCliente(0, "Tipo Cliente"));
            for (TipoCliente tc : tipoCliente) {
                cmbTipoCliente.addItem(tc);
            }

            // Si quieres llenar meses
            cmbMes.removeAllItems();
            cmbMes.addItem("Mes");
            String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
                "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
            for (String m : meses) {
                cmbMes.addItem(m);
            }

            // Si quieres llenar años (ejemplo 2020–2025)
            cmbAnio.removeAllItems();
            cmbAnio.addItem("Año");
            for (int i = 2020; i <= 2025; i++) {
                cmbAnio.addItem(String.valueOf(i));
            }

        } catch (Excepciones ex) {
            Logger.getLogger(GestionClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelRound14 = new jilmar.PanelRound();
        lblRol = new jilmar.LabelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnVolverMenu = new jilmar.LabelRound();
        pnlListaEmpleados = new jilmar.PanelRound();
        ScrollMasVentas = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnClientes = new jilmar.LabelRound();
        lblResumen2 = new javax.swing.JLabel();
        btnGestionEmpleados = new jilmar.LabelRound();
        panelRound3 = new jilmar.PanelRound();
        cmbAnio = new javax.swing.JComboBox<>();
        panelRound4 = new jilmar.PanelRound();
        cmbTipoCliente = new javax.swing.JComboBox<>();
        panelRound5 = new jilmar.PanelRound();
        cmbMes = new javax.swing.JComboBox<>();
        btnBuscar = new jilmar.LabelRound();
        jLabel1 = new javax.swing.JLabel();
        panelActions = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound14.setBackground(new Color(255, 255, 255,80));
        panelRound14.setRoundBottomLeft(30);
        panelRound14.setRoundBottomRight(30);
        panelRound14.setRoundTopLeft(30);
        panelRound14.setRoundTopRight(30);
        panelRound14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRol.setBackground(new java.awt.Color(153, 255, 153));
        lblRol.setForeground(new java.awt.Color(0, 51, 153));
        lblRol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRol.setText("VENDEDOR");
        lblRol.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        lblRol.setRoundBottomLeft(30);
        lblRol.setRoundBottomRight(30);
        lblRol.setRoundTopLeft(30);
        lblRol.setRoundTopRight(30);
        panelRound14.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 25, 90, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_icon_50x50.png"))); // NOI18N
        panelRound14.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 15, 50, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registro de Ventas");
        panelRound14.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 15, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Computadores y Componentes");
        panelRound14.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 45, -1, -1));

        lblUser.setFont(new java.awt.Font("JetBrains Mono NL ExtraBold", 0, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Jilmar Gonzalez");
        panelRound14.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        jLabel22.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Usuario:");
        panelRound14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        btnVolverMenu.setBackground(new java.awt.Color(11, 61, 120));
        btnVolverMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolverMenu.setText("Volver al Menu");
        btnVolverMenu.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        btnVolverMenu.setRoundBottomLeft(50);
        btnVolverMenu.setRoundBottomRight(50);
        btnVolverMenu.setRoundTopLeft(50);
        btnVolverMenu.setRoundTopRight(50);
        btnVolverMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMenuMouseExited(evt);
            }
        });
        panelRound14.add(btnVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 170, 40));

        jPanel1.add(panelRound14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1140, 80));

        pnlListaEmpleados.setBackground(new Color(255, 255, 255, 230));
        pnlListaEmpleados.setRoundBottomLeft(30);
        pnlListaEmpleados.setRoundBottomRight(30);
        pnlListaEmpleados.setRoundTopLeft(30);
        pnlListaEmpleados.setRoundTopRight(30);
        pnlListaEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Usuario", "Rol", "Fecha Ingreso", "Aciones"
            }
        ));
        tblClientes.setEnabled(false);
        tblClientes.setOpaque(false);
        ScrollMasVentas.setViewportView(tblClientes);
        if (tblClientes.getColumnModel().getColumnCount() > 0) {
            tblClientes.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        pnlListaEmpleados.add(ScrollMasVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 750, 310));

        btnClientes.setBackground(new java.awt.Color(0, 204, 255));
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClientes.setText("Todos los Clientes");
        btnClientes.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        btnClientes.setRoundBottomLeft(40);
        btnClientes.setRoundBottomRight(40);
        btnClientes.setRoundTopLeft(40);
        btnClientes.setRoundTopRight(40);
        btnClientes.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
        });
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Al entrar el mouse, se aplica solo un color (puedes usar un gradiente de un solo color si tu botón lo permite)
                btnClientes.setGradientHorizontal(new Color(2, 114, 185), new Color(2, 114, 185));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Al salir el mouse, se vuelve al gradiente original
                btnClientes.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
            }
        });
        pnlListaEmpleados.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 220, 40));

        lblResumen2.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 20)); // NOI18N
        lblResumen2.setForeground(new java.awt.Color(0, 51, 153));
        lblResumen2.setText("Historial de Ventas");
        pnlListaEmpleados.add(lblResumen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        btnGestionEmpleados.setBackground(new java.awt.Color(153, 153, 153));
        btnGestionEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGestionEmpleados.setText("Gestion Clientes");
        btnGestionEmpleados.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        btnGestionEmpleados.setRoundBottomLeft(40);
        btnGestionEmpleados.setRoundBottomRight(40);
        btnGestionEmpleados.setRoundTopLeft(40);
        btnGestionEmpleados.setRoundTopRight(40);
        btnGestionEmpleados.setBackground(new Color(153, 153, 153));
        btnGestionEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionEmpleadosMouseClicked(evt);
            }
        });
        btnGestionEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Cuando el mouse entra, se oscurece
                btnGestionEmpleados.setBackground(new Color(102, 102, 102));
            }
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Cuando el mouse sale, vuelve al original
                btnGestionEmpleados.setBackground(new Color(153, 153, 153));
            }
        });
        pnlListaEmpleados.add(btnGestionEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 220, 40));

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(15);
        panelRound3.setRoundBottomRight(15);
        panelRound3.setRoundTopLeft(15);
        panelRound3.setRoundTopRight(15);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbAnio.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 12)); // NOI18N
        cmbAnio.setBorder(null);
        panelRound3.add(cmbAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 40));

        pnlListaEmpleados.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 145, 40));

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(15);
        panelRound4.setRoundBottomRight(15);
        panelRound4.setRoundTopLeft(15);
        panelRound4.setRoundTopRight(15);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbTipoCliente.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 12)); // NOI18N
        cmbTipoCliente.setBorder(null);
        panelRound4.add(cmbTipoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 40));

        pnlListaEmpleados.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 145, 40));

        panelRound5.setBackground(new java.awt.Color(255, 255, 255));
        panelRound5.setRoundBottomLeft(15);
        panelRound5.setRoundBottomRight(15);
        panelRound5.setRoundTopLeft(15);
        panelRound5.setRoundTopRight(15);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbMes.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 12)); // NOI18N
        cmbMes.setBorder(null);
        panelRound5.add(cmbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 40));

        pnlListaEmpleados.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 145, 40));

        btnBuscar.setBackground(new java.awt.Color(0, 204, 255));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setText("Buscar");
        btnBuscar.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        btnBuscar.setRoundBottomLeft(40);
        btnBuscar.setRoundBottomRight(40);
        btnBuscar.setRoundTopLeft(40);
        btnBuscar.setRoundTopRight(40);
        btnBuscar.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Al entrar el mouse, se aplica solo un color (puedes usar un gradiente de un solo color si tu botón lo permite)
                btnBuscar.setGradientHorizontal(new Color(2, 114, 185), new Color(2, 114, 185));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Al salir el mouse, se vuelve al gradiente original
                btnBuscar.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
            }
        });
        pnlListaEmpleados.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 100, 140, 40));

        jPanel1.add(pnlListaEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 1140, 530));

        panelMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 670));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondo_completo.png"))); // NOI18N
        panelMain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 670));

        getContentPane().add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1220, 670));

        panelActions.setBackground(new java.awt.Color(215, 235, 255));
        panelActions.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelActionsMouseDragged(evt);
            }
        });
        panelActions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelActionsMousePressed(evt);
            }
        });
        panelActions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_icono.png"))); // NOI18N
        panelActions.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        lblTitle.setBackground(new java.awt.Color(0, 51, 153));
        lblTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 153));
        lblTitle.setText("ITIN-PC Mundo Tecnologico");
        panelActions.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 0, -1, 30));

        btnMinimize.setBackground(new java.awt.Color(215, 235, 255));
        btnMinimize.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMinimize.setForeground(new java.awt.Color(0, 51, 153));
        btnMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize.setText("-");
        btnMinimize.setOpaque(true);
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        panelActions.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 50, 30));

        btnExit.setBackground(new java.awt.Color(215, 235, 255));
        btnExit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 51, 153));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        panelActions.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 50, 30));

        getContentPane().add(panelActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 30));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionEmpleadosMouseClicked
        new GestionClientes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionEmpleadosMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setBackground(Color.gray);
        btnMinimize.setForeground(Color.white);
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        btnMinimize.setBackground(new Color(215, 235, 255));
        btnMinimize.setForeground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(Color.red);
        btnExit.setForeground(Color.white);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new Color(215, 235, 255));
        btnExit.setForeground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnExitMouseExited

    private void panelActionsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActionsMouseDragged
        int x = getLocation().x + evt.getX() - initX;
        int y = getLocation().y + evt.getY() - initY;
        this.setLocation(x, y);
    }//GEN-LAST:event_panelActionsMouseDragged

    private void panelActionsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActionsMousePressed
        initX = evt.getX();
        initY = evt.getY();
    }//GEN-LAST:event_panelActionsMousePressed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        aplicarFiltros();
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        verTodosLosClientes();
        reiniciarFiltros();
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnVolverMenuMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnVolverMenuMouseClicked
        new MenuPrincipal(SesionUsuario.obtenerUsuarioActual()).setVisible(true);
        this.dispose();
    }// GEN-LAST:event_btnVolverMenuMouseClicked

    private void btnVolverMenuMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnVolverMenuMouseEntered
        btnVolverMenu.setBackground(new Color(4, 177, 233));
    }// GEN-LAST:event_btnVolverMenuMouseEntered

    private void btnVolverMenuMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnVolverMenuMouseExited
        btnVolverMenu.setBackground(new Color(11, 61, 120));
    }// GEN-LAST:event_btnVolverMenuMouseExited

    private void verTodosLosClientes() {
        try {
            listaClientesBD = new ArrayList<>(c.obtenerClientes());
            listaClientesFiltrados = new ArrayList<>(listaClientesBD);
            actualizarTabla();
        } catch (Excepciones ex) {
            Logger.getLogger(GestionClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void aplicarFiltros() {
        String mes = (String) cmbMes.getSelectedItem();
        String anio = (String) cmbAnio.getSelectedItem();
        String tipoClientes = ((TipoCliente) cmbTipoCliente.getSelectedItem()).getTipo();

        try {
            List<Cliente> listaFiltrada = c.obtenerClientesPorTipo(tipoClientes, obtenerNumeroMes(mes), Integer.parseInt(anio));

            if (!listaFiltrada.isEmpty()) {
                listaClientesFiltrados = listaFiltrada;
            }

            if (!listaClientesFiltrados.isEmpty()) {
                actualizarTabla();
            }
        } catch (Excepciones ex) {
            Logger.getLogger(ReportesCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void reiniciarFiltros() {
        cmbTipoCliente.setSelectedIndex(0);
        cmbMes.setSelectedIndex(0);
        cmbAnio.setSelectedIndex(0);
    }

    private void actualizarTabla() {
        modeloTabla.setRowCount(0);
        for (Cliente cliente : listaClientesFiltrados) {
            Object[] fila = {
                cliente.getId(),
                cliente.getNombre() + " " + cliente.getApellido(),
                cliente.getTelefono(),
                cliente.getCorreo(),
                tipoCliente(cliente.getTipoClienteId())
            };
            modeloTabla.addRow(fila);
        }
        tblClientes.setModel(modeloTabla);
    }

    private String tipoCliente(int tipoClienteId) {
        try {
            List<TipoCliente> tipoClientes = c.obtenerTiposCliente();
            for (TipoCliente tc : tipoClientes) {
                if (tc.getId() == tipoClienteId) {
                    return tc.getTipo();
                }
            }
        } catch (Excepciones e) {
            Logger.getLogger(GestionClientes.class.getName()).log(Level.SEVERE, null, e);
        }

        return "";
    }

    private int obtenerNumeroMes(String mes) {
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
            "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        for (int i = 0; i < meses.length; i++) {
            if (meses[i].equalsIgnoreCase(mes)) {
                return i + 1; // Enero = 1
            }
        }
        return 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollMasVentas;
    private jilmar.LabelRound btnBuscar;
    private jilmar.LabelRound btnClientes;
    private javax.swing.JLabel btnExit;
    private jilmar.LabelRound btnGestionEmpleados;
    private javax.swing.JLabel btnMinimize;
    private jilmar.LabelRound btnVolverMenu;
    private javax.swing.JComboBox<String> cmbAnio;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JComboBox<TipoCliente> cmbTipoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblResumen2;
    private jilmar.LabelRound lblRol;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel panelActions;
    private javax.swing.JPanel panelMain;
    private jilmar.PanelRound panelRound14;
    private jilmar.PanelRound panelRound3;
    private jilmar.PanelRound panelRound4;
    private jilmar.PanelRound panelRound5;
    private jilmar.PanelRound pnlListaEmpleados;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables

    // Propiedasdes de la tabla
    private void propiedadTabla() {

        String[] columnas = {"ID", "Nombre", "telefono", "Correo", "Tipo Cliente"};
        modeloTabla = new DefaultTableModel(columnas, 0);

        tblClientes = new JTable(modeloTabla);
        tblClientes.setRowHeight(36);
        tblClientes.setFont(new java.awt.Font("JetBrains Mono SemiBoldd", 0, 12));
        tblClientes.getTableHeader().setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 12));
        tblClientes.getTableHeader().setBackground(new Color(4, 178, 234));
        tblClientes.getTableHeader().setForeground(Color.white);
        tblClientes.getTableHeader().setPreferredSize(new Dimension(100, 36));

        ScrollMasVentas.setViewportView(tblClientes);

        // Configurar el ancho de las columnas
        if (tblClientes.getColumnModel().getColumnCount() > 0) {
            tblClientes.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblClientes.getColumnModel().getColumn(1).setPreferredWidth(20);
            tblClientes.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblClientes.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblClientes.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        // Centrar el texto de las celdas
        tblClientes.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (c instanceof JLabel label) {
                    label.setHorizontalAlignment(SwingConstants.CENTER);
                    label.setVerticalAlignment(SwingConstants.CENTER);
                    label.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 12));

                }
                return c;
            }
        });

        ScrollMasVentas.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));

    }

}
