package itin_pc.view;

import itin_pc.controller.EmpleadoControlador;
import itin_pc.controller.ProductoControlador;
import itin_pc.controller.ServicioTecnicoControlador;
import itin_pc.controller.VentaControlador;
import itin_pc.model.Empleado;
import itin_pc.model.Marca;
import itin_pc.model.ReporteEmpleados;
import itin_pc.model.ReporteServicioTecnico;
import itin_pc.model.Usuario;
import itin_pc.model.Venta;
import itin_pc.util.Excepciones;
import itin_pc.util.SesionUsuario;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class ReportesEmpleado extends javax.swing.JFrame {

    private DefaultTableModel modeloTablaMasVentas;
    private DefaultTableModel modeloTablaServicioTenico;

    private final EmpleadoControlador e;
    private final VentaControlador v;
    private final ProductoControlador p;
    private final ServicioTecnicoControlador stc;

    List<ReporteEmpleados> reporteEmpleados;
    List<ReporteServicioTecnico> reporteServicioTecnico;

    Usuario usuario;
    Empleado empleado;

    private int initX, initY;
    private boolean bandera = true;

    public ReportesEmpleado() {

        this.e = new EmpleadoControlador();
        this.v = new VentaControlador();
        this.p = new ProductoControlador();
        this.stc = new ServicioTecnicoControlador();

        this.usuario = SesionUsuario.obtenerUsuarioActual();

        initComponents();
        this.setLocationRelativeTo(null);
        aplicarComboBox();

        this.bandera = false;

        propiedadTablaMasVentas();
        propiedadTablaReparaciones();

        configuracionRol();

        verReporteEmpleadosConMasVentas();
    }

    private void configuracionRol() {

        try {
            this.empleado = e.obtenerEmpleado(usuario.getId());

            String rol = usuario.getRol();
            String nombre = empleado.getNombre() + " " + empleado.getApellido();

            lblUser.setText(nombre);
            lblRol.setText(rol);

        } catch (Excepciones ex) {
            Logger.getLogger(ReportesEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void aplicarComboBox() {
        try {

            List<Marca> marcas = p.obtenerMarcas();

            cmbMarcas.removeAllItems();
            cmbMarcas.addItem(new Marca(0, "Marcas"));

            for (Marca marca : marcas) {
                cmbMarcas.addItem(marca);
            }

        } catch (Excepciones ex) {
            Logger.getLogger(ReportesEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelRound14 = new jilmar.PanelRound();
        lblRol = new jilmar.LabelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnVolverMenu = new jilmar.LabelRound();
        pnlListaEmpleados = new jilmar.PanelRound();
        ScrollMasVentas = new javax.swing.JScrollPane();
        tblReporteMasVentas = new javax.swing.JTable();
        ScrollReparaciones = new javax.swing.JScrollPane();
        tblReporteReparaciones = new javax.swing.JTable();
        btnMasVentas = new jilmar.LabelRound();
        btnReparaciones = new jilmar.LabelRound();
        lblResumen2 = new javax.swing.JLabel();
        pnlMarcas = new jilmar.PanelRound();
        cmbMarcas = new javax.swing.JComboBox<>();
        btnGestionEmpleados = new jilmar.LabelRound();
        jLabel1 = new javax.swing.JLabel();
        panelActions = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound14.setBackground(new Color(255, 255, 255,80));
        panelRound14.setRoundBottomLeft(30);
        panelRound14.setRoundBottomRight(30);
        panelRound14.setRoundTopLeft(30);
        panelRound14.setRoundTopRight(30);
        panelRound14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRol.setBackground(new java.awt.Color(153, 255, 153));
        lblRol.setForeground(new java.awt.Color(0, 51, 153));
        lblRol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRol.setText("VENDEDOR");
        lblRol.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        lblRol.setRoundBottomLeft(30);
        lblRol.setRoundBottomRight(30);
        lblRol.setRoundTopLeft(30);
        lblRol.setRoundTopRight(30);
        panelRound14.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 25, 90, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_icon_50x50.png"))); // NOI18N
        panelRound14.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 15, 50, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Reporte de Empleados");
        panelRound14.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 15, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Computadores y Componentes");
        panelRound14.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 45, -1, -1));

        lblUser.setFont(new java.awt.Font("JetBrains Mono NL ExtraBold", 0, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Jilmar Gonzalez");
        panelRound14.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        jLabel22.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Usuario:");
        panelRound14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        btnVolverMenu.setBackground(new java.awt.Color(11, 61, 120));
        btnVolverMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolverMenu.setText("Volver al Menu");
        btnVolverMenu.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        btnVolverMenu.setRoundBottomLeft(50);
        btnVolverMenu.setRoundBottomRight(50);
        btnVolverMenu.setRoundTopLeft(50);
        btnVolverMenu.setRoundTopRight(50);
        btnVolverMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMenuMouseExited(evt);
            }
        });
        panelRound14.add(btnVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 170, 40));

        jPanel1.add(panelRound14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1140, 80));

        pnlListaEmpleados.setBackground(new Color(255, 255, 255, 230));
        pnlListaEmpleados.setRoundBottomLeft(30);
        pnlListaEmpleados.setRoundBottomRight(30);
        pnlListaEmpleados.setRoundTopLeft(30);
        pnlListaEmpleados.setRoundTopRight(30);
        pnlListaEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblReporteMasVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Usuario", "Rol", "Fecha Ingreso", "Aciones"
            }
        ));
        tblReporteMasVentas.setEnabled(false);
        tblReporteMasVentas.setOpaque(false);
        ScrollMasVentas.setViewportView(tblReporteMasVentas);
        if (tblReporteMasVentas.getColumnModel().getColumnCount() > 0) {
            tblReporteMasVentas.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        pnlListaEmpleados.add(ScrollMasVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 750, 390));

        tblReporteReparaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Usuario", "Rol", "Fecha Ingreso", "Aciones"
            }
        ));
        tblReporteReparaciones.setEnabled(false);
        tblReporteReparaciones.setOpaque(false);
        ScrollReparaciones.setViewportView(tblReporteReparaciones);
        if (tblReporteReparaciones.getColumnModel().getColumnCount() > 0) {
            tblReporteReparaciones.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        ScrollReparaciones.setVisible(false);

        pnlListaEmpleados.add(ScrollReparaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 750, 390));

        btnMasVentas.setBackground(new java.awt.Color(0, 204, 255));
        btnMasVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnMasVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMasVentas.setText("Empleados con Mas Ventas");
        btnMasVentas.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        btnMasVentas.setRoundBottomLeft(40);
        btnMasVentas.setRoundBottomRight(40);
        btnMasVentas.setRoundTopLeft(40);
        btnMasVentas.setRoundTopRight(40);
        btnMasVentas.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
        btnMasVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasVentasMouseClicked(evt);
            }
        });
        btnMasVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Al entrar el mouse, se aplica solo un color (puedes usar un gradiente de un solo color si tu botón lo permite)
                btnMasVentas.setGradientHorizontal(new Color(2, 114, 185), new Color(2, 114, 185));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Al salir el mouse, se vuelve al gradiente original
                btnMasVentas.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
            }
        });
        pnlListaEmpleados.add(btnMasVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 220, 40));

        btnReparaciones.setBackground(new java.awt.Color(0, 204, 255));
        btnReparaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnReparaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReparaciones.setText("Reparaciones por Marca");
        btnReparaciones.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        btnReparaciones.setRoundBottomLeft(40);
        btnReparaciones.setRoundBottomRight(40);
        btnReparaciones.setRoundTopLeft(40);
        btnReparaciones.setRoundTopRight(40);
        btnReparaciones.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
        btnReparaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReparacionesMouseClicked(evt);
            }
        });
        btnReparaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Al entrar el mouse, se aplica solo un color (puedes usar un gradiente de un solo color si tu botón lo permite)
                btnReparaciones.setGradientHorizontal(new Color(2, 114, 185), new Color(2, 114, 185));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Al salir el mouse, se vuelve al gradiente original
                btnReparaciones.setGradientHorizontal(new Color(4, 178, 234), new Color(2, 114, 185));
            }
        });
        pnlListaEmpleados.add(btnReparaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 220, 40));

        lblResumen2.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 20)); // NOI18N
        lblResumen2.setForeground(new java.awt.Color(0, 51, 153));
        lblResumen2.setText("Reporte");
        pnlListaEmpleados.add(lblResumen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        pnlMarcas.setBackground(new java.awt.Color(255, 255, 255));
        pnlMarcas.setRoundBottomLeft(40);
        pnlMarcas.setRoundBottomRight(40);
        pnlMarcas.setRoundTopLeft(40);
        pnlMarcas.setRoundTopRight(40);
        pnlMarcas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlMarcas.setVisible(false);

        cmbMarcas.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 12)); // NOI18N
        cmbMarcas.setBorder(null);
        cmbMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMarcasActionPerformed(evt);
            }
        });
        pnlMarcas.add(cmbMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 180, 40));

        pnlListaEmpleados.add(pnlMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 220, 40));

        btnGestionEmpleados.setBackground(new java.awt.Color(153, 153, 153));
        btnGestionEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGestionEmpleados.setText("Gestion Empleados");
        btnGestionEmpleados.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 14)); // NOI18N
        btnGestionEmpleados.setRoundBottomLeft(40);
        btnGestionEmpleados.setRoundBottomRight(40);
        btnGestionEmpleados.setRoundTopLeft(40);
        btnGestionEmpleados.setRoundTopRight(40);
        btnGestionEmpleados.setBackground(new Color(153, 153, 153));
        btnGestionEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionEmpleadosMouseClicked(evt);
            }
        });
        btnGestionEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Cuando el mouse entra, se oscurece
                btnGestionEmpleados.setBackground(new Color(102, 102, 102));
            }
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Cuando el mouse sale, vuelve al original
                btnGestionEmpleados.setBackground(new Color(153, 153, 153));
            }
        });
        pnlListaEmpleados.add(btnGestionEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 220, 40));

        jPanel1.add(pnlListaEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 1140, 530));

        panelMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 670));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondo_completo.png"))); // NOI18N
        panelMain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 670));

        getContentPane().add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1220, 670));

        panelActions.setBackground(new java.awt.Color(215, 235, 255));
        panelActions.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelActionsMouseDragged(evt);
            }
        });
        panelActions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelActionsMousePressed(evt);
            }
        });
        panelActions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_icono.png"))); // NOI18N
        panelActions.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        lblTitle.setBackground(new java.awt.Color(0, 51, 153));
        lblTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 153));
        lblTitle.setText("ITIN-PC Mundo Tecnologico");
        panelActions.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 0, -1, 30));

        btnMinimize.setBackground(new java.awt.Color(215, 235, 255));
        btnMinimize.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMinimize.setForeground(new java.awt.Color(0, 51, 153));
        btnMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize.setText("-");
        btnMinimize.setOpaque(true);
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        panelActions.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 50, 30));

        btnExit.setBackground(new java.awt.Color(215, 235, 255));
        btnExit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 51, 153));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        panelActions.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 50, 30));

        getContentPane().add(panelActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 30));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionEmpleadosMouseClicked
        new GestionEmpleados().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionEmpleadosMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setBackground(Color.gray);
        btnMinimize.setForeground(Color.white);
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        btnMinimize.setBackground(new Color(215, 235, 255));
        btnMinimize.setForeground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(Color.red);
        btnExit.setForeground(Color.white);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new Color(215, 235, 255));
        btnExit.setForeground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnExitMouseExited

    private void panelActionsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActionsMouseDragged
        int x = getLocation().x + evt.getX() - initX;
        int y = getLocation().y + evt.getY() - initY;
        this.setLocation(x, y);
    }//GEN-LAST:event_panelActionsMouseDragged

    private void panelActionsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActionsMousePressed
        initX = evt.getX();
        initY = evt.getY();
    }//GEN-LAST:event_panelActionsMousePressed

    private void btnVolverMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMenuMouseClicked
        new MenuPrincipal(SesionUsuario.obtenerUsuarioActual()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverMenuMouseClicked

    private void btnVolverMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMenuMouseEntered
        btnVolverMenu.setBackground(new Color(4, 177, 233));
    }//GEN-LAST:event_btnVolverMenuMouseEntered

    private void btnVolverMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMenuMouseExited
        btnVolverMenu.setBackground(new Color(11, 61, 120));
    }//GEN-LAST:event_btnVolverMenuMouseExited

    private void btnMasVentasMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnMasVentasMouseClicked
        pnlMarcas.setVisible(false);
        ScrollReparaciones.setVisible(false);
        ScrollMasVentas.setVisible(true);
        verReporteEmpleadosConMasVentas();
    }// GEN-LAST:event_btnMasVentasMouseClicked

    private void btnReparacionesMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnReparacionesMouseClicked
        pnlMarcas.setVisible(true);
        ScrollMasVentas.setVisible(false);
        ScrollReparaciones.setVisible(true);
    }// GEN-LAST:event_btnReparacionesMouseClicked

    private void cmbMarcasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmbMarcasActionPerformed
        if (!bandera) {
            String nombreMarca = ((Marca) cmbMarcas.getSelectedItem()).getNombre();
            verReporteServiciosTecnicos(nombreMarca);
        }
    }// GEN-LAST:event_cmbMarcasActionPerformed

    private void verReporteEmpleadosConMasVentas() {
        try {
            if (reporteEmpleados == null) {
                reporteEmpleados = new ArrayList<>(e.empleadosConMasVentas());
            }
            actualizarTablaMasVentas();
        } catch (Excepciones ex) {
            Logger.getLogger(ReportesEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void actualizarTablaMasVentas() {
        modeloTablaMasVentas.setRowCount(0);
        int posicion = 1;
        for (ReporteEmpleados reporte : reporteEmpleados) {
            Object[] fila = {
                    posicion,
                    reporte.getId(),
                    reporte.getNombre() + " " + reporte.getApellido(),
                    reporte.getNumeroVentas(),
                    reporte.getMontoTotal(),
                    obtenerUltimaVenta(reporte.getId()).getFecha(), };
            modeloTablaMasVentas.addRow(fila);
            posicion++;
        }
        tblReporteMasVentas.setModel(modeloTablaMasVentas);
    }

    private Venta obtenerUltimaVenta(int ventaId) {
        Venta venta = null;
        try {
            venta = v.obtenerVentaPorId(ventaId);
        } catch (Excepciones ex) {
            Logger.getLogger(ReportesEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        return venta;
    }

    private void verReporteServiciosTecnicos(String marca) {
        try {
            reporteServicioTecnico = new ArrayList<>(stc.obtenerReportesPorMarca(marca));
            actualizarTablaReparaciones();

        } catch (Excepciones ex) {
            Logger.getLogger(ReportesEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void actualizarTablaReparaciones() {
        modeloTablaServicioTenico.setRowCount(0);
        for (ReporteServicioTecnico servicio : reporteServicioTecnico) {
            Object[] fila = {
                    servicio.getNombreProducto(),
                    servicio.getMarcaProducto(),
                    servicio.getTipoServicio(),
                    servicio.getFechaServicio(),
                    servicio.getProblemasReportados()
            };
            modeloTablaServicioTenico.addRow(fila);
        }
        tblReporteReparaciones.setModel(modeloTablaServicioTenico);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollMasVentas;
    private javax.swing.JScrollPane ScrollReparaciones;
    private javax.swing.JLabel btnExit;
    private jilmar.LabelRound btnGestionEmpleados;
    private jilmar.LabelRound btnMasVentas;
    private javax.swing.JLabel btnMinimize;
    private jilmar.LabelRound btnReparaciones;
    private jilmar.LabelRound btnVolverMenu;
    private javax.swing.JComboBox<Marca> cmbMarcas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblResumen2;
    private jilmar.LabelRound lblRol;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel panelActions;
    private javax.swing.JPanel panelMain;
    private jilmar.PanelRound panelRound14;
    private jilmar.PanelRound pnlListaEmpleados;
    private jilmar.PanelRound pnlMarcas;
    private javax.swing.JTable tblReporteMasVentas;
    private javax.swing.JTable tblReporteReparaciones;
    // End of variables declaration//GEN-END:variables

    // Propiedasdes de la tabla
    private void propiedadTablaMasVentas() {

        String[] columnas = { "Posicion", "ID", "Nombre", "Total Ventas", "Monto Total", "Ultima Venta" };
        modeloTablaMasVentas = new DefaultTableModel(columnas, 0);

        tblReporteMasVentas = new JTable(modeloTablaMasVentas);
        tblReporteMasVentas.setRowHeight(36);
        tblReporteMasVentas.setFont(new java.awt.Font("JetBrains Mono SemiBoldd", 0, 12));
        tblReporteMasVentas.getTableHeader().setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 12));
        tblReporteMasVentas.getTableHeader().setBackground(new Color(4, 178, 234));
        tblReporteMasVentas.getTableHeader().setForeground(Color.white);
        tblReporteMasVentas.getTableHeader().setPreferredSize(new Dimension(100, 36));

        ScrollMasVentas.setViewportView(tblReporteMasVentas);

        // Configurar el ancho de las columnas
        if (tblReporteMasVentas.getColumnModel().getColumnCount() > 0) {
            tblReporteMasVentas.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblReporteMasVentas.getColumnModel().getColumn(1).setPreferredWidth(20);
            tblReporteMasVentas.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblReporteMasVentas.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblReporteMasVentas.getColumnModel().getColumn(4).setPreferredWidth(50);
            tblReporteMasVentas.getColumnModel().getColumn(5).setPreferredWidth(80);
        }

        // Centrar el texto de las celdas
        tblReporteMasVentas.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (c instanceof JLabel label) {
                    label.setHorizontalAlignment(SwingConstants.CENTER);
                    label.setVerticalAlignment(SwingConstants.CENTER);
                    label.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 12));

                }
                return c;
            }
        });

        ScrollMasVentas.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));

    }

    private void propiedadTablaReparaciones() {

        String[] columnas = { "Nombre Producto", "Marca", "Tipo Servicio", "Fecha Servicio",
                "Problemas Reportados" };
        modeloTablaServicioTenico = new DefaultTableModel(columnas, 0);

        tblReporteReparaciones = new JTable(modeloTablaServicioTenico);
        tblReporteReparaciones.setRowHeight(36);
        tblReporteReparaciones.setFont(new java.awt.Font("JetBrains Mono SemiBoldd", 0, 12));
        tblReporteReparaciones.getTableHeader().setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 12));
        tblReporteReparaciones.getTableHeader().setBackground(new Color(4, 178, 234));
        tblReporteReparaciones.getTableHeader().setForeground(Color.white);
        tblReporteReparaciones.getTableHeader().setPreferredSize(new Dimension(100, 36));

        ScrollReparaciones.setViewportView(tblReporteReparaciones);

        // Configurar el ancho de las columnas
        if (tblReporteReparaciones.getColumnModel().getColumnCount() > 0) {
            tblReporteReparaciones.getColumnModel().getColumn(0).setPreferredWidth(90);
            tblReporteReparaciones.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblReporteReparaciones.getColumnModel().getColumn(2).setPreferredWidth(40);
            tblReporteReparaciones.getColumnModel().getColumn(3).setPreferredWidth(40);
            tblReporteReparaciones.getColumnModel().getColumn(4).setPreferredWidth(120);
        }

        // Centrar el texto de las celdas
        tblReporteReparaciones.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (c instanceof JLabel label) {
                    label.setHorizontalAlignment(SwingConstants.CENTER);
                    label.setVerticalAlignment(SwingConstants.CENTER);
                    label.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 12));

                }
                return c;
            }
        });

        ScrollReparaciones.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));

    }

}
